#!/bin/bash
#================================================
function gk_string(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9) {
    i = 0 ; lArgMap[i++] = p0 ; lArgMap[i++] = p1 ; lArgMap[i++] = p2 ; lArgMap[i++] = p3 ; lArgMap[i++] = p4 ; lArgMap[i++] = p5 ; lArgMap[i++] = p6 ; lArgMap[i++] = p7 ; lArgMap[i++] = p8 ; lArgMap[i++] = p9
    lLength = i;
    for(i = 0; i < lLength; ) {
        lKey = lArgMap[i++]
        if(lKey == "") break
        # trim
        if(lKey == "trim") {
            lString = lArgMap[i++]
            return GString_trim(lString)
        }
    }
}
#================================================
function GString_trim_left(str) {
    sub(/^[ \t\r\n]+/, "", str) ; 
    return str
}
#================================================
function GString_trim_right(str) {
    sub(/[ \t\r\n]+$/, "", str) ; 
    return str
}
#================================================
function GString_trim(str) {
    return GString_trim_right(GString_trim_left(str))
}
#================================================
function GString_get_char(str) {
    return substr(str, pos, 1)
}
#================================================
