#!/bin/bash
#================================================
GPWD=$PWD
#================================================
. $GPATH/.config
#================================================
lCheckIn="GPATH" ; if [ "${!lCheckIn}" = "" ] || ! [ -d "${!lCheckIn}" ] ; then echo "ERREUR : ${lCheckIn} ?" ; exit ; fi 
lCheckIn="GOPT_PATH" ; if [ "${!lCheckIn}" = "" ] || ! [ -d "${!lCheckIn}" ] ; then echo "ERREUR : ${lCheckIn} ?" ; exit ; fi 
#================================================
lPath=$GOPT_PATH/certbot_auto
if ! [ -d "$lPath" ] ; then mkdir -p $lPath ; fi
cd $lPath
wget https://dl.eff.org/certbot-auto
chmod a+x ./certbot-auto
#================================================
cd $GPWD
#================================================
