#!/bin/bash
#================================================
GPWD=$PWD
#================================================
lCheckIn="GPATH" ; if [ "${!lCheckIn}" = "" ] || ! [ -d "${!lCheckIn}" ] ; then echo "ERREUR : ${lCheckIn} ?" ; exit ; fi 
#================================================
. $GPATH/.config
#================================================
lCheckIn="GPKG_CONFIG_PATH" ; if [ "${!lCheckIn}" = "" ] || ! [ -d "${!lCheckIn}" ] ; then echo "ERREUR : ${lCheckIn} ?" ; exit ; fi 
#================================================
# Configurations
printf "\n"
printf "Configurations :\n"
printf "\t%-20s : %s\n" "GPKG_CONFIG_PATH" "$GPKG_CONFIG_PATH"
printf "\n"
#================================================
read -p "Confirmation de continuer (Oui|[N]on) ? " lAnswer
case $lAnswer in
    [Oo]* ) echo "OUI : operation effectuee" ; echo ;;
    * ) echo "NON : operation annulee" ; echo ; exit ;;
esac
#================================================
ls $GPKG_CONFIG_PATH
echo
#================================================
cd $GPWD
#================================================
