#!/bin/bash
#================================================
function GString_trim_left(s) {
sub(/^[ \t\r\n]+/, "", s) ; 
return s
}
#================================================
function GString_trim_right(s) {
sub(/[ \t\r\n]+$/, "", s) ; 
return s
}
#================================================
function GString_trim(s) {
return GString_trim_right(GString_trim_left(s))
}
#================================================
