#!/bin/bash
#================================================
GPWD=$PWD
#================================================
G_STATE="S_INIT"
#================================================
GAptGet_Main() {
while [ 1 ] ; do
case "$G_STATE" in 
    "S_ADMIN") GAptGet_ADMIN ;;
    "S_INIT") GAptGet_INIT ;;
    "S_METHOD") GAptGet_METHOD ;;
    "S_CHOICE") GAptGet_CHOICE ;;
    #
    "S_PACKAGE_LIST") GAptGet_PACKAGE_LIST ;;
    "S_PACKAGE_UPDATE") GAptGet_PACKAGE_UPDATE ;;
    #
    "S_PACKAGE_LIST_FILTER_PACKAGE_FILTER") GAptGet_PACKAGE_LIST_FILTER_PACKAGE_FILTER ;;
    "S_PACKAGE_LIST_FILTER") GAptGet_PACKAGE_LIST_FILTER ;;
    #
    "S_PACKAGE_SEARCH_PACKAGE_FILTER") GAptGet_PACKAGE_SEARCH_PACKAGE_FILTER ;;
    "S_PACKAGE_SEARCH") GAptGet_PACKAGE_SEARCH ;;
    #
    "S_PACKAGE_INSTALL_PACKAGE_FILTER") GAptGet_PACKAGE_INSTALL_PACKAGE_FILTER ;;
    "S_PACKAGE_INSTALL") GAptGet_PACKAGE_INSTALL ;;
    #
    "S_SAVE") GAptGet_SAVE ;;
    "S_LOAD") GAptGet_LOAD ;;
    "S_QUIT") GAptGet_QUIT ;;
    *) break ;;
esac    
done
}
#================================================
GAptGet_ADMIN() {
gz_admin
G_STATE="S_END"
}
#================================================
GAptGet_INIT() {
printf "\n"
printf "APT_GET !!!\n"
printf "\t%2s : %s\n" "-q" "quitter l'application"
printf "\t%2s : %s\n" "-i" "reinitialiser l'application"
printf "\t%2s : %s\n" "-a" "redemarrer l'administration"
printf "\t%2s : %s\n" "-v" "valider les configurations"
printf "\n"
G_STATE="S_LOAD"
}
#================================================
GAptGet_METHOD() {
printf "APT_GET :\n"
printf "\t%2s : %s\n" "1" "lister les packages installes"
printf "\t%2s : %s\n" "2" "lister les packages installes par filtrage"
printf "\t%2s : %s\n" "3" "mettre a jour les packages"
printf "\t%2s : %s\n" "4" "rechercher un package"
printf "\t%2s : %s\n" "5" "installer un package"
printf "\n"
G_STATE="S_CHOICE"
}
#================================================
GAptGet_CHOICE() {
read -p "APT_GET ($G_APT_GET_ID) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_APT_GET_ID" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
#
elif [ "$lAnswer" = "1" ] ; then G_STATE="S_PACKAGE_LIST" ; G_APT_GET_ID="$lAnswer"
elif [ "$lAnswer" = "2" ] ; then G_STATE="S_PACKAGE_LIST_FILTER_PACKAGE_FILTER" ; G_APT_GET_ID="$lAnswer"
elif [ "$lAnswer" = "3" ] ; then G_STATE="S_PACKAGE_UPDATE" ; G_APT_GET_ID="$lAnswer"
elif [ "$lAnswer" = "4" ] ; then G_STATE="S_PACKAGE_SEARCH_PACKAGE_FILTER" ; G_APT_GET_ID="$lAnswer"
elif [ "$lAnswer" = "5" ] ; then G_STATE="S_PACKAGE_INSTALL_PACKAGE_NAME" ; G_APT_GET_ID="$lAnswer"
fi
}
#================================================
GAptGet_PACKAGE_INSTALL_PACKAGE_NAME() {
read -p "G_PACKAGE_NAME ($G_PACKAGE_NAME) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_PACKAGE_NAME" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "-v" ] ; then G_STATE="S_PACKAGE_INSTALL" ; G_PACKAGE_NAME="$lAnswer"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_PACKAGE_INSTALL" ; G_PACKAGE_NAME="$lAnswer"
fi
}
#================================================
GAptGet_PACKAGE_INSTALL() {
echo
sudo apt-get install "$G_PACKAGE_NAME"
G_STATE="S_SAVE"
}
#================================================
GAptGet_PACKAGE_SEARCH_PACKAGE_FILTER() {
read -p "G_PACKAGE_FILTER ($G_PACKAGE_FILTER) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_PACKAGE_FILTER" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "-v" ] ; then G_STATE="S_PACKAGE_SEARCH" ; G_PACKAGE_FILTER="$lAnswer"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_PACKAGE_SEARCH" ; G_PACKAGE_FILTER="$lAnswer"
fi
}
#================================================
GAptGet_PACKAGE_SEARCH() {
echo
apt-cache search "$G_PACKAGE_FILTER"
G_STATE="S_SAVE"
}
#================================================
GAptGet_PACKAGE_UPDATE() {
echo
sudo apt-get update
G_STATE="S_SAVE"
}
#================================================
GAptGet_PACKAGE_LIST_FILTER_PACKAGE_FILTER() {
read -p "G_PACKAGE_FILTER ($G_PACKAGE_FILTER) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_PACKAGE_FILTER" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "-v" ] ; then G_STATE="S_PACKAGE_LIST_FILTER" ; G_PACKAGE_FILTER="$lAnswer"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_PACKAGE_LIST_FILTER" ; G_PACKAGE_FILTER="$lAnswer"
fi
}
#================================================
GAptGet_PACKAGE_LIST_FILTER() {
echo
apt list --installed | \
grep -iE "$G_PACKAGE_FILTER"
G_STATE="S_SAVE"
}
#================================================
GAptGet_PACKAGE_LIST() {
echo
apt list --installed
G_STATE="S_SAVE"
}
#================================================
GAptGet_SAVE() {
gz_process_in "config_save" "G_APT_GET_ID" "$G_APT_GET_ID"
gz_process_in "config_save" "G_PACKAGE_FILTER" "$G_PACKAGE_FILTER"
gz_process_in "config_save" "G_PACKAGE_NAME" "$G_PACKAGE_NAME"
G_STATE="S_QUIT"
}
#================================================
GAptGet_LOAD() {
G_APT_GET_ID=$(gz_process_in "config_load" "G_APT_GET_ID")
G_PACKAGE_FILTER=$(gz_process_in "config_load" "G_PACKAGE_FILTER")
G_PACKAGE_NAME=$(gz_process_in "config_load" "G_PACKAGE_NAME")
G_STATE="S_METHOD"
}
#================================================
GAptGet_QUIT() {
echo
read -p "APT_GET_QUIT (Oui/[N]on) ? " lAnswer
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "o" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "n" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "" ] ; then G_STATE="S_INIT"
fi
}
#================================================
GAptGet_Main
#================================================
cd $GPWD
#================================================
