#!/bin/bash
#================================================
GPWD=$PWD
#================================================
GBIN_PATH=/home/pi/Programs/ReadyStudio/ReadyBin
GPATH=/home/pi/Programs/ReadyStudio/ReadyBin/unix
#================================================
export AWKPATH="$GPATH/awk"
#================================================
GAwk_main() {
lArgSize="$#"
if [ "$lArgSize" = "0" ] ; then GAwk_help "$@"
else GAwk_process "$@" ; fi
}
#================================================
GAwk_help() {
lScript=$(gz_string filename "$0")
GSCRIPT="\t\033[0;35m${lScript}\033[0m"
GCOMMENT="\033[0;33m%s\033[0m"
GHELP="$GSCRIPT : $GCOMMENT\n"
GREQUEST="\033[36m%s\033[0m"
GPROCESS="$GSCRIPT $GREQUEST : $GCOMMENT\n"
printf "\n"
printf "%s\n" "Description:"
printf "\t%s\n" "Operations sur les commandes awk."
printf "\n"
printf "%s\n" "Utilisation:"
printf "$GHELP" "afficher aide"
printf "$GPROCESS" "t <module_in>" "tester module"
printf "\n"
}
#================================================
GAwk_process() {
lArgSize="$#"
lArgCount=1
lRunFlag=0
while [ 1 ] ; do
if [ "$lArgCount" -gt "$lArgSize" ] ; then break ; fi
lKey=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
# t
if [ "$lKey" = "t" ] ; then 
lModule=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
GAwk_module_test "$lModule" ; lRunFlag=1
#
fi
done
if [ "$lRunFlag" = "0" ] ; then GAwk_help ; fi 
}
#================================================
GAwk_module_test() {
local lModule=$1
awk -i $lModule -v gk_func="$lModule" 'BEGIN {@gk_func("test")}'
}
#================================================
GAwk_main "$@"
#================================================
