#!/bin/bash
#================================================
GPWD=$PWD
#================================================
G_STATE="S_INIT"
#================================================
GApache_Main() {
while [ 1 ] ; do
case "$G_STATE" in 
    "S_ADMIN") GApache_ADMIN ;;
    "S_INIT") GApache_INIT ;;
    "S_METHOD") GApache_METHOD ;;
    "S_CHOICE") GApache_CHOICE ;;
    #

    #
    "S_SAVE") GApache_SAVE ;;
    "S_LOAD") GApache_LOAD ;;
    "S_QUIT") GApache_QUIT ;;
    *) break ;;
esac    
done
}
#================================================
GApache_ADMIN() {
gz_admin
G_STATE="S_SAVE"
}
#================================================
GApache_INIT() {
printf "\n"
printf "VIEWS !!!\n"
printf "\t%2s : %s\n" "-q" "quitter l'application"
printf "\t%2s : %s\n" "-i" "reinitialiser l'application"
printf "\t%2s : %s\n" "-a" "redemarrer l'administration"
printf "\t%2s : %s\n" "-v" "valider les configurations"
printf "\n"
G_STATE="S_LOAD"
}
#================================================
GApache_METHOD() {
printf "VIEWS :\n"
printf "\t%2s : %s\n" "1" "activer un module"
printf "\t%2s : %s\n" "2" "desactiver un module"
printf "\t%2s : %s\n" "3" "recharger les configs"
printf "\t%2s : %s\n" "4" "verifier l'etat d'un module"
printf "\t%2s : %s\n" "5" "lister les modules"
printf "\t%2s : %s\n" "6" "redemarrer le serveur"
printf "\n"
G_STATE="S_CHOICE"
}
#================================================
GApache_CHOICE() {
read -p "VIEWS ($G_APACHE_ID) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_APACHE_ID" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
#
elif [ "$lAnswer" = "1" ] ; then G_STATE="S_ENABLE" ; G_APACHE_ID="$lAnswer"
elif [ "$lAnswer" = "2" ] ; then G_STATE="S_DISABLE" ; G_APACHE_ID="$lAnswer"
elif [ "$lAnswer" = "3" ] ; then G_STATE="S_RELOAD" ; G_APACHE_ID="$lAnswer"
elif [ "$lAnswer" = "4" ] ; then G_STATE="S_MOD_STATUS" ; G_APACHE_ID="$lAnswer"
elif [ "$lAnswer" = "5" ] ; then G_STATE="S_MOD_LIST" ; G_APACHE_ID="$lAnswer"
elif [ "$lAnswer" = "6" ] ; then G_STATE="S_RESTART" ; G_APACHE_ID="$lAnswer"
fi
}
#================================================
GApache_DELETE_READYDEV_DB() {
read -p "G_READYDEV_DB ($G_READYDEV_DB) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_READYDEV_DB" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_DELETE_VIEW_KEY" ; G_READYDEV_DB="$lAnswer"
fi
}
#================================================
GApache_Point() {
sudo a2enmod rewrite
sudo a2dismod rewrite
sudo service apache2 reload
sudo a2query -m rewrite
sudo a2query -m
}
#================================================
GApache_SAVE() {
gz_process_in "config_save" "G_APACHE_ID" "$G_APACHE_ID"
G_STATE="S_QUIT"
}
#================================================
GApache_LOAD() {
G_APACHE_ID=$(gz_process_in "config_load" "G_APACHE_ID")
G_STATE="S_METHOD"
}
#================================================
GApache_QUIT() {
echo
read -p "VIEWS_QUIT (Oui/[N]on) ? " lAnswer
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "o" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "n" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "" ] ; then G_STATE="S_INIT"
fi
}
#================================================
GApache_Main
#================================================
cd $GPWD
#================================================
