#!/bin/bash
#================================================
GPWD=$PWD
#================================================
. $GPATH/.config
#================== ==============================
lCheckIn="GPATH" ; if [ "${!lCheckIn}" = "" ] || ! [ -d "${!lCheckIn}" ] ; then echo $(gz_color s "$lCheckIn ?" yellow fg) ; exit ; fi 
lCheckIn="GANDROID_PATH" ; if [ "${!lCheckIn}" = "" ] || ! [ -d "${!lCheckIn}" ] ; then echo $(gz_color s "$lCheckIn ?" yellow fg) ; exit ; fi 
#================================================
export PATH=$GANDROID_PATH/Sdk/tools:$PATH
export PATH=$GANDROID_PATH/Sdk/tools/bin:$PATH
export PATH=$GANDROID_PATH/Sdk/platform-tools:$PATH
#================================================
adb shell
am start  -n com.package.name/com.package.name.ActivityName
#================================================
