#!/bin/bash
#================================================
GPWD=$PWD
#================================================
G_STATE="S_INIT"
#================================================
GAdmin_Main() {
while [ 1 ] ; do
case "$G_STATE" in 
    "S_INIT") GAdmin_INIT ;;
    "S_METHOD") GAdmin_METHOD ;;
    "S_CHOICE") GAdmin_CHOICE ;;
    #
    "S_BIN") GAdmin_BIN ;;
    #
    "S_PACMAN") GAdmin_PACMAN ;;
    "S_SQLITE") GAdmin_SQLITE ;;
    "S_GIT") GAdmin_GIT ;;
    "S_APACHE") GAdmin_APACHE ;;
    #
    "S_CONFIG") GAdmin_CONFIG ;;
    "S_VIEWS") GAdmin_VIEWS ;;
    #
    "S_SAVE") GAdmin_SAVE ;;
    "S_LOAD") GAdmin_LOAD ;;
    *) break ;;
esac    
done
}
#================================================
GAdmin_INIT() {
printf "\n"
printf "### ADMINISTRATION ###\n"
printf "\t%2s : %s\n" "-q" "quitter l'application"
printf "\n"
G_STATE="S_LOAD"
}
#================================================
GAdmin_METHOD() {
printf "ADMINISTRATION :\n"
printf "\t%2s : %s\n" "1" "BIN"
printf "\n"
printf "\t%2s : %s\n" "10" "PACMAN"
printf "\t%2s : %s\n" "11" "SQLITE"
printf "\t%2s : %s\n" "12" "GIT"
printf "\t%2s : %s\n" "13" "APACHE"
printf "\n"
printf "\t%2s : %s\n" "20" "CONFIG"
printf "\t%2s : %s\n" "21" "VIEWS"
printf "\n"
G_STATE="S_CHOICE"
}
#================================================
GAdmin_CHOICE() {
read -p "ADMINISTRATION ($G_ADMIN_ID) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_ADMIN_ID" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
#
elif [ "$lAnswer" = "1" ] ; then G_STATE="S_BIN" ; G_ADMIN_ID="$lAnswer"
#
elif [ "$lAnswer" = "10" ] ; then G_STATE="S_PACMAN" ; G_ADMIN_ID="$lAnswer"
elif [ "$lAnswer" = "11" ] ; then G_STATE="S_SQLITE" ; G_ADMIN_ID="$lAnswer"
elif [ "$lAnswer" = "12" ] ; then G_STATE="S_GIT" ; G_ADMIN_ID="$lAnswer"
elif [ "$lAnswer" = "13" ] ; then G_STATE="S_APACHE" ; G_ADMIN_ID="$lAnswer"
#
elif [ "$lAnswer" = "20" ] ; then G_STATE="S_CONFIG" ; G_ADMIN_ID="$lAnswer"
elif [ "$lAnswer" = "21" ] ; then G_STATE="S_VIEWS" ; G_ADMIN_ID="$lAnswer"
fi
}
#================================================
GAdmin_BIN() {
gz_bin
G_STATE="S_SAVE"
}
#================================================
GAdmin_PACMAN() {
gz_pacman
G_STATE="S_SAVE"
}
#================================================
GAdmin_SQLITE() {
gz_sqlite
G_STATE="S_SAVE"
}
#================================================
GAdmin_GIT() {
gz_git
G_STATE="S_SAVE"
}
#================================================
GAdmin_APACHE() {
gz_apache
G_STATE="S_SAVE"
}
#================================================
GAdmin_CONFIG() {
gz_config
G_STATE="S_SAVE"
}
#================================================
GAdmin_VIEWS() {
gz_views
G_STATE="S_SAVE"
}
#================================================
GAdmin_SAVE() {
gz_config_edit_in "G_ADMIN_ID" "$G_ADMIN_ID"
G_STATE="S_END"
}
#================================================
GAdmin_LOAD() {
G_ADMIN_ID=$(gz_config_read_in "G_ADMIN_ID")
G_STATE="S_METHOD"
}
#================================================
GAdmin_Main
#================================================
cd $GPWD
#================================================
