#!/bin/bash
#================================================
GPWD=$PWD
#================================================
lCheckIn="GPATH" ; if [ "${!lCheckIn}" = "" ] || ! [ -d "${!lCheckIn}" ] ; then echo "ERREUR : ${lCheckIn} ?" ; exit ; fi 
#================================================
. $GPATH/.config
#================================================
lCheckIn="GBIN_PATH" ; if [ "${!lCheckIn}" = "" ] || ! [ -d "${!lCheckIn}" ] ; then echo "ERREUR : ${lCheckIn} ?" ; exit ; fi 
#================================================
# Configurations
printf "\n"
printf "Configurations :\n"
printf "\t%-20s : %s\n" "GBIN_PATH" "$GBIN_PATH"
printf "\n"
#================================================
read -p "Confirmation (Oui|[N]on) ? " lAnswer
case $lAnswer in
    [Oo]* ) echo "OUI : operation effectuee" ; echo ;;
    * ) echo "NON : operation annulee" ; echo ; exit ;;
esac
#================================================
cd $GBIN_PATH
sudo git add --all
sudo git commit -m "Initial Commit"
sudo git push -u origin master
#================================================
cd $GPWD
#================================================
