#!/bin/bash
#================================================
GPWD=$PWD
#================================================
G_STATE="S_INIT"
#================================================
GBin_Main() {
while [ 1 ] ; do
case "$G_STATE" in 
    "S_ADMIN") GBin_ADMIN ;;
    "S_INIT") GBin_INIT ;;
    "S_METHOD") GBin_METHOD ;;
    "S_CHOICE") GBin_CHOICE ;;
    #
    "S_CREATE_SCRIPT_NAME") GBin_CREATE_SCRIPT_NAME ;;
    "S_CREATE") GBin_CREATE ;;
    #
    "S_SAVE") GBin_SAVE ;;
    "S_LOAD") GBin_LOAD ;;
    "S_QUIT") GBin_QUIT ;;
    *) break ;;
esac    
done
}
#================================================
GBin_ADMIN() {
gz_admin
G_STATE="S_SAVE"
}
#================================================
GBin_INIT() {
printf "\n"
printf "BIN !!!\n"
printf "\t%2s : %s\n" "-q" "quitter l'application"
printf "\t%2s : %s\n" "-i" "reinitialiser l'application"
printf "\t%2s : %s\n" "-a" "redemarrer l'administration"
printf "\t%2s : %s\n" "-v" "valider les configurations"
printf "\n"
G_STATE="S_LOAD"
}
#================================================
GBin_METHOD() {
printf "BIN :\n"
printf "\t%2s : %s\n" "1" "creer un script"
printf "\n"
G_STATE="S_CHOICE"
}
#================================================
GBin_CHOICE() {
read -p "BIN ($G_BIN_ID) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_BIN_ID" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
#
elif [ "$lAnswer" = "1" ] ; then G_STATE="S_CREATE_SCRIPT_NAME" ; G_BIN_ID="$lAnswer"
fi
}
#================================================
GBin_CREATE_SCRIPT_NAME() {
read -p "G_SCRIPT_NAME ($G_SCRIPT_NAME) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_SCRIPT_NAME" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "-v" ] ; then G_STATE="S_CREATE" ; G_SCRIPT_NAME="$lAnswer"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_CREATE" ; G_SCRIPT_NAME="$lAnswer"
fi
}
#================================================
GBin_CREATE() {
cd $GPATH
vim $G_SCRIPT_NAME
G_STATE="S_SAVE"
}
#================================================
GBin_SAVE() {
gz_process_in "config_save" "G_BIN_ID" "$G_BIN_ID"
gz_process_in "config_save" "G_SCRIPT_NAME" "$G_SCRIPT_NAME"
G_STATE="S_QUIT"
}
#================================================
GBin_LOAD() {
G_BIN_ID=$(gz_process_in "config_load" "G_BIN_ID")
G_SCRIPT_NAME=$(gz_process_in "config_load" "G_SCRIPT_NAME")
G_STATE="S_METHOD"
}
#================================================
GBin_QUIT() {
echo
read -p "VIEWS_QUIT (Oui/[N]on) ? " lAnswer
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "o" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "n" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "" ] ; then G_STATE="S_INIT"
fi
}
#================================================
GBin_Main
#================================================
cd $GPWD
#================================================
