#!/bin/bash
#================================================
GPWD=$PWD
#================================================
GBIN_PATH="C:\Users\Admin\Downloads\Programs\ReadyBin";GBIN_PATH=$(gz_cygwin c "$GBIN_PATH")
#================================================
GBin_main() {
lArgSize="$#"
if [ "$lArgSize" = "0" ] ; then GBin_help "$@"
else GBin_process "$@" ; fi
}
#================================================
GBin_help() {
lScript=$(gz_string filename "$0")
GSCRIPT="\t\033[0;35m${lScript}\033[0m"
GCOMMENT="\033[0;33m%s\033[0m"
GHELP="$GSCRIPT : $GCOMMENT\n"
GREQUEST="\033[36m%s\033[0m"
GPROCESS="$GSCRIPT $GREQUEST : $GCOMMENT\n"
printf "\n"
printf "%s\n" "Description:"
printf "\t%s\n" "Operations sur les chaines de caracteres."
printf "\n"
printf "%s\n" "Utilisation:"
printf "$GHELP" "afficher aide"
printf "$GPROCESS" "set <string_in>" "colorier chaine"
printf "\n"
}
#================================================
GBin_process() {
lArgSize="$#"
lArgCount=1
lRunFlag=0
while [ 1 ] ; do
if [ "$lArgCount" -gt "$lArgSize" ] ; then break ; fi
lKey=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
# git_s
if [ "$lKey" = "git_s" ] ; then 
GBin_git_status ; lRunFlag=1
# git_a
elif [ "$lKey" = "git_a" ] ; then 
GBin_git_add_all ; lRunFlag=1
#
fi
done
if [ "$lRunFlag" = "0" ] ; then GBin_help ; fi 
}
#================================================
GBin_git_status() {
cd $GBIN_PATH
git status
cd $GPWD
}
#================================================
GBin_git_add_all() {
cd $GBIN_PATH
git add --all
cd $GPWD
}
#================================================
GBin_main "$@"
#================================================
