#!/bin/bash
#================================================
GPWD=$PWD
#================================================
G_STATE="S_INIT"
#================================================
GCerbot_Main() {
while [ 1 ] ; do
case "$G_STATE" in 
    "S_ADMIN") GCerbot_ADMIN ;;
    "S_INIT") GCerbot_INIT ;;
    "S_METHOD") GCerbot_METHOD ;;
    "S_CHOICE") GCerbot_CHOICE ;;
    #
    "S_CERT_LIST") GCerbot_CERT_LIST ;;
    "S_CERT_RENEW") GCerbot_CERT_RENEW ;;
    #
    "S_SAVE") GCerbot_SAVE ;;
    "S_LOAD") GCerbot_LOAD ;;
    "S_QUIT") GCerbot_QUIT ;;
    *) break ;;
esac    
done
}
#================================================
GCerbot_ADMIN() {
gz_admin
G_STATE="S_END"
}
#================================================
GCerbot_INIT() {
printf "\n"
printf "CERBOT !!!\n"
printf "\t%2s : %s\n" "-q" "quitter l'application"
printf "\t%2s : %s\n" "-i" "reinitialiser l'application"
printf "\t%2s : %s\n" "-a" "redemarrer l'administration"
printf "\t%2s : %s\n" "-v" "valider les configurations"
printf "\n"
G_STATE="S_LOAD"
}
#================================================
GCerbot_METHOD() {
printf "CERBOT :\n"
printf "\t%2s : %s\n" "1" "lister les certificats"
printf "\t%2s : %s\n" "2" "renouveller les certificats"
printf "\n"
G_STATE="S_CHOICE"
}
#================================================
GCerbot_CHOICE() {
read -p "CERBOT ($G_CERBOT_ID) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_CERBOT_ID" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
#
elif [ "$lAnswer" = "1" ] ; then G_STATE="S_CERT_LIST" ; G_CERBOT_ID="$lAnswer"
elif [ "$lAnswer" = "2" ] ; then G_STATE="S_CERT_RENEW" ; G_CERBOT_ID="$lAnswer"
#
fi
}
#================================================
GCerbot_CERT_RENEW() {
echo
. $GPATH/.env
certbot-auto renew
G_STATE="S_SAVE"
}
#================================================
GCerbot_CERT_LIST() {
echo
. $GPATH/.env
certbot-auto certificates
G_STATE="S_SAVE"
}
#================================================
GCerbot_SAVE() {
gz_process_in "config_save" "G_CERBOT_ID" "$G_CERBOT_ID"
G_STATE="S_QUIT"
}
#================================================
GCerbot_LOAD() {
G_CERBOT_ID=$(gz_process_in "config_load" "G_CERBOT_ID")
G_STATE="S_METHOD"
}
#================================================
GCerbot_QUIT() {
echo
read -p "QUIT (Oui/[N]on) ? " lAnswer
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "o" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "n" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "" ] ; then G_STATE="S_INIT"
fi
}
#================================================
GCerbot_Main
#================================================
cd $GPWD
#================================================
