#!/bin/bash
#================================================
# Reset
GCOLOR_OFF='\033[0m'             # Text Reset
#================================================
# Regular Colors
GCOLOR_FG_BLACK='\033[0;30m'     # Black
GCOLOR_FG_RED='\033[0;31m'       # Red
GCOLOR_FG_GREEN='\033[0;32m'     # Green
GCOLOR_FG_YELLOW='\033[0;33m'    # Yellow
GCOLOR_FG_BLUE='\033[0;34m'      # Blue
GCOLOR_FG_PURPLE='\033[0;35m'    # Purple
GCOLOR_FG_CYAN='\033[0;36m'      # Cyan
GCOLOR_FG_WHITE='\033[0;37m'     # White
#================================================
# Background
GCOLOR_BG_BLACK='\033[40m'       # Black
GCOLOR_BG_RED='\033[41m'         # Red
GCOLOR_BG_GREEN='\033[42m'       # Green
GCOLOR_BG_YELLOW='\033[43m'      # Yellow
GCOLOR_BG_BLUE='\033[44m'        # Blue
GCOLOR_BG_PURPLE='\033[45m'      # Purple
GCOLOR_BG_CYAN='\033[46m'        # Cyan
GCOLOR_BG_WHITE='\033[47m'       # White
#================================================
# Bold
GCOLOR_BD_BLACK='\033[1;30m'     # Black
GCOLOR_BD_RED='\033[1;31m'       # Red
GCOLOR_BD_GREEN='\033[1;32m'     # Green
GCOLOR_BD_YELLOW='\033[1;33m'    # Yellow
GCOLOR_BD_BLUE='\033[1;34m'      # Blue
GCOLOR_BD_PURPLE='\033[1;35m'    # Purple
GCOLOR_BD_CYAN='\033[1;36m'      # Cyan
GCOLOR_BD_WHITE='\033[1;37m'     # White
#================================================
# Underline
GCOLOR_UL_BLACK='\033[4;30m'     # Black
GCOLOR_UL_RED='\033[4;31m'       # Red
GCOLOR_UL_GREEN='\033[4;32m'     # Green
GCOLOR_UL_YELLOW='\033[4;33m'    # Yellow
GCOLOR_UL_BLUE='\033[4;34m'      # Blue
GCOLOR_UL_PURPLE='\033[4;35m'    # Purple
GCOLOR_UL_CYAN='\033[4;36m'      # Cyan
GCOLOR_UL_WHITE='\033[4;37m'     # White
#================================================
# High Intensity
GCOLOR_HI_BLACK='\033[0;90m'     # Black
GCOLOR_HI_RED='\033[0;91m'       # Red
GCOLOR_HI_GREEN='\033[0;92m'     # Green
GCOLOR_HI_YELLOW='\033[0;93m'    # Yellow
GCOLOR_HI_BLUE='\033[0;94m'      # Blue
GCOLOR_HI_PURPLE='\033[0;95m'    # Purple
GCOLOR_HI_CYAN='\033[0;96m'      # Cyan
GCOLOR_HI_WHITE='\033[0;97m'     # White
#================================================
# Bold High Intensity
GCOLOR_BI_BLACK='\033[1;90m'     # Black
GCOLOR_BI_RED='\033[1;91m'       # Red
GCOLOR_BI_GREEN='\033[1;92m'     # Green
GCOLOR_BI_YELLOW='\033[1;93m'    # Yellow
GCOLOR_BI_BLUE='\033[1;94m'      # Blue
GCOLOR_BI_PURPLE='\033[1;95m'    # Purple
GCOLOR_BI_CYAN='\033[1;96m'      # Cyan
GCOLOR_BI_WHITE='\033[1;97m'     # White
#================================================
# High Intensity backgrounds
GCOLOR_HB_BLACK='\033[0;100m'    # Black
GCOLOR_HB_RED='\033[0;101m'      # Red
GCOLOR_HB_GREEN='\033[0;102m'    # Green
GCOLOR_HB_YELLOW='\033[0;103m'   # Yellow
GCOLOR_HB_BLUE='\033[0;104m'     # Blue
GCOLOR_HB_PURPLE='\033[0;105m'   # Purple
GCOLOR_HB_CYAN='\033[0;106m'     # Cyan
GCOLOR_HB_WHITE='\033[0;107m'    # White
#================================================
GPWD=$PWD
#================================================
GColor_main() {
lArgSize="$#"
if [ "$lArgSize" = "0" ] ; then GColor_help "$@"
else GColor_process "$@" ; fi
}
#================================================
GColor_help() {
lScript=$(gz_string filename "$0")
GSCRIPT="\t\033[0;35m${lScript}\033[0m"
GCOMMENT="\033[0;33m%s\033[0m"
GHELP="$GSCRIPT : $GCOMMENT\n"
GREQUEST="\033[36m%s\033[0m"
GPROCESS="$GSCRIPT $GREQUEST : $GCOMMENT\n"
printf "\n"
printf "%s\n" "Description:"
printf "\t%s\n" "Operations sur les chaines de caracteres."
printf "\n"
printf "%s\n" "Utilisation:"
printf "$GHELP" "afficher aide"
printf "$GPROCESS" "set <string_in>" "colorier chaine"
printf "$GPROCESS" "get <color_in> <key_in>" "lire couleur"
printf "\n"
}
#================================================
GColor_process() {
lArgSize="$#"
lArgCount=1
lRunFlag=0
while [ 1 ] ; do
if [ "$lArgCount" -gt "$lArgSize" ] ; then break ; fi
lKey=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
# set
if [ "$lKey" = "set" ] ; then 
lString=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
lName=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
lKey=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
GColor_set "$lString" "$lName" "$lKey" ; lRunFlag=1
# get
elif [ "$lKey" = "get" ] ; then 
lName=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
lKey=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
GColor_get "$lName" "$lKey" ; lRunFlag=1
#
fi
done
if [ "$lRunFlag" = "0" ] ; then GColor_help ; fi 
}
#================================================
GColor_set() {
local lString=$1
local lName=$2
local lKey=$3
lColor=$(GColor_get "$lName" "$lKey")
printf "${lColor}%s${GCOLOR_OFF}" "$lString"
}
#================================================
GColor_get() {
local lColorName=$1
local lColorKey=$2
lColorName=$(gz_string to_upper "$lColorName")
lColorKey=$(gz_string to_upper "$lColorKey")
lColor="GCOLOR_${lColorKey}_${lColorName}"
lColor=${!lColor}
echo "$lColor"
}
#================================================
GColor_main "$@"
#================================================
