#!/bin/bash
#================================================
GPWD=$PWD
#================================================
GCONFIG_ROOT=/home/pi/Programs/ReadyStudio/ReadyBin/unix
GCONFIG_NAME=.config
GCONFIG_PATH=$GCONFIG_ROOT/$GCONFIG_NAME
#================================================
export AWKPATH="$GCONFIG_ROOT/awk"
#================================================
GConfig_main() {
lArgSize="$#"
if [ "$lArgSize" = "0" ] ; then GConfig_help "$@"
else GConfig_process "$@" ; fi
}
#================================================
GConfig_help() {
lScript=$(gz_string filename "$0")
GSCRIPT="\t\033[0;35m${lScript}\033[0m"
GCOMMENT="\033[0;33m%s\033[0m"
GHELP="$GSCRIPT : $GCOMMENT\n"
GREQUEST="\033[36m%s\033[0m"
GPROCESS="$GSCRIPT $GREQUEST : $GCOMMENT\n"
printf "\n"
printf "%s\n" "Description:"
printf "\t%s\n" "Operations sur les configurations."
printf "\n"
printf "%s\n" "Utilisation:"
printf "$GHELP" "afficher aide"
printf "$GPROCESS" "init_c" "initialiser config"
printf "$GPROCESS" "init_p" "initialiser chemin"
printf "$GPROCESS" "get_p" "lire chemin"
printf "\n"
}
#================================================
GConfig_process() {
lArgSize="$#"
lArgCount=1
lRunFlag=0
while [ 1 ] ; do
if [ "$lArgCount" -gt "$lArgSize" ] ; then break ; fi
lKey=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
# init_c
if [ "$lKey" = "init_c" ] ; then 
GConfig_init_config ; lRunFlag=1
# init_p
elif [ "$lKey" = "init_p" ] ; then 
GConfig_init_path ; lRunFlag=1
# get_p
elif [ "$lKey" = "get_p" ] ; then 
GConfig_get_path ; lRunFlag=1
#
fi
done
if [ "$lRunFlag" = "0" ] ; then GConfig_help ; fi 
}
#================================================
GConfig_init_config() {
if ! [ -f "$GCONFIG_PATH" ] ; then
mkdir -p $GCONFIG_ROOT
> $GCONFIG_PATH
fi
}
#================================================
GConfig_init_path() {
GConfig_check_path gpath
return
echo "GPATH=$GCONFIG_ROOT" >> $GCONFIG_PATH
}
#================================================
GConfig_check_path() {
local lPath=$1
if [ "$lPath" = "" ] ; then echo $(gz_color s "path ?" yellow fg) ; return ; fi 
GConfig_init_config
awk -F "=" -v lPath="$lPath" -i gk_string '
BEGIN {print lPath}
{lLine = $0
if(lLine == "") next
lLine = gk_string("trim", $lLine)
if(lLine == "") next
lFirstChar = gk_string("get_c", lLine, 0)
if(lFirstChar == "#") next
lCount = gk_string("split_c", lLine, "=")
if(lCount < 2) next
lKey = gk_string("split", lLine, "=", 1)
lValue = gk_string("split", lLine, "=", 2)
printf("%s:%s\n", lKey, lValue)
}' $GCONFIG_PATH
 }
#================================================
GConfig_get_path() {
echo $GCONFIG_PATH
}
#================================================
GConfig_main "$@"
#================================================
