#!/bin/bash
#================================================
GPWD=$PWD
#================================================
G_STATE="S_INIT"
#================================================
GCpp_Main() {
while [ 1 ] ; do
case "$G_STATE" in 
    "S_ADMIN") GCpp_ADMIN ;;
    "S_INIT") GCpp_INIT ;;
    "S_METHOD") GCpp_METHOD ;;
    "S_CHOICE") GCpp_CHOICE ;;
    #
    "S_CPP_COMPILE_CPP_PATH") GCpp_CPP_COMPILE_CPP_PATH ;;
    "S_CPP_COMPILE_CPP_NAME") GCpp_CPP_COMPILE_CPP_NAME ;;
    "S_CPP_COMPILE") GCpp_CPP_COMPILE ;;
    #
    "S_CPP_CLEAN_CPP_PATH") GCpp_CPP_CLEAN_CPP_PATH ;;
    "S_CPP_CLEAN_CPP_NAME") GCpp_CPP_CLEAN_CPP_NAME ;;
    "S_CPP_CLEAN") GCpp_CPP_CLEAN ;;
    #
    "S_QT_COMPILE_QT_PATH") GCpp_QT_COMPILE_QT_PATH ;;
    "S_QT_COMPILE_QT_NAME") GCpp_QT_COMPILE_QT_NAME ;;
    "S_QT_COMPILE") GCpp_QT_COMPILE ;;
    #
    "S_SAVE") GCpp_SAVE ;;
    "S_LOAD") GCpp_LOAD ;;
    "S_QUIT") GCpp_QUIT ;;
    *) break ;;
esac    
done
}
#================================================
GCpp_ADMIN() {
gz_admin
G_STATE="S_END"
}
#================================================
GCpp_INIT() {
printf "\n"
printf "CPP !!!\n"
printf "\t%2s : %s\n" "-q" "quitter l'application"
printf "\t%2s : %s\n" "-i" "reinitialiser l'application"
printf "\t%2s : %s\n" "-a" "redemarrer l'administration"
printf "\t%2s : %s\n" "-v" "valider les configurations"
printf "\n"
G_STATE="S_LOAD"
}
#================================================
GCpp_METHOD() {
printf "CPP :\n"
printf "\t%2s : %s\n" "1" "compiler un projet"
printf "\t%2s : %s\n" "2" "nettoyer un projet"
printf "\n"
printf "\t%2s : %s\n" "10" "compiler un projet QT"
printf "\n"
G_STATE="S_CHOICE"
}
#================================================
GCpp_CHOICE() {
read -p "CPP ($G_CPP_ID) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_CPP_ID" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
#
elif [ "$lAnswer" = "1" ] ; then G_STATE="S_CPP_COMPILE_CPP_PATH" ; G_CPP_ID="$lAnswer"
elif [ "$lAnswer" = "2" ] ; then G_STATE="S_CPP_CLEAN_CPP_PATH" ; G_CPP_ID="$lAnswer"
#
elif [ "$lAnswer" = "2" ] ; then G_STATE="S_QT_COMPILE_QT_PATH" ; G_CPP_ID="$lAnswer"
#
fi
}
#================================================
GCpp_QT_COMPILE_QT_PATH() {
read -p "G_QT_PATH ($G_QT_PATH) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_QT_PATH" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "-v" ] ; then G_STATE="S_QT_COMPILE"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_QT_COMPILE_QT_NAME" ; G_QT_PATH="$lAnswer"
fi
}
#================================================
GCpp_QT_COMPILE_QT_NAME() {
read -p "G_QT_NAME ($G_QT_NAME) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_QT_NAME" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "-v" ] ; then G_STATE="S_QT_COMPILE"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_QT_COMPILE" ; G_QT_NAME="$lAnswer"
fi
}
#================================================
GCpp_QT_COMPILE() {
echo
lBuildPath="$G_QT_PATH/$G_QT_NAME/unix"
lMakefile="Makefile.qmake"
cd $lBuildPath
make -f "$lMakefile" all
G_STATE="S_SAVE"
}
#================================================
GCpp_CPP_COMPILE_CPP_PATH() {
read -p "G_CPP_PATH ($G_CPP_PATH) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_CPP_PATH" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "-v" ] ; then G_STATE="S_CPP_COMPILE"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_CPP_COMPILE_CPP_NAME" ; G_CPP_PATH="$lAnswer"
fi
}
#================================================
GCpp_CPP_COMPILE_CPP_NAME() {
read -p "G_CPP_NAME ($G_CPP_NAME) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_CPP_NAME" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "-v" ] ; then G_STATE="S_CPP_COMPILE"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_CPP_COMPILE" ; G_CPP_NAME="$lAnswer"
fi
}
#================================================
GCpp_CPP_COMPILE() {
echo
lBuldPath="$G_CPP_PATH/$G_CPP_NAME/unix"
lMakefile="Makefile.unix"
cd $lBuldPath
make -f "$lMakefile" all
G_STATE="S_SAVE"
}
#================================================
GCpp_CPP_CLEAN_CPP_PATH() {
read -p "G_CPP_PATH ($G_CPP_PATH) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_CPP_PATH" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "-v" ] ; then G_STATE="S_CPP_CLEAN"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_CPP_CLEAN_CPP_NAME" ; G_CPP_PATH="$lAnswer"
fi
}
#================================================
GCpp_CPP_CLEAN_CPP_NAME() {
read -p "G_CPP_NAME ($G_CPP_NAME) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_CPP_NAME" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "-v" ] ; then G_STATE="S_CPP_CLEAN"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_CPP_CLEAN" ; G_CPP_NAME="$lAnswer"
fi
}
#================================================
GCpp_CPP_CLEAN() {
echo
lBuldPath="$G_CPP_PATH/$G_CPP_NAME/unix"
lMakefile="Makefile.unix"
cd $lBuldPath
make -f "$lMakefile" clean
G_STATE="S_SAVE"
}
#================================================
GCpp_SAVE() {
gz_process_in "config_save" "G_CPP_ID" "$G_CPP_ID"
gz_process_in "config_save" "G_CPP_PATH" "$G_CPP_PATH"
gz_process_in "config_save" "G_CPP_NAME" "$G_CPP_NAME"
gz_process_in "config_save" "G_QT_PATH" "$G_QT_PATH"
gz_process_in "config_save" "G_QT_NAME" "$G_QT_NAME"
G_STATE="S_QUIT"
}
#================================================
GCpp_LOAD() {
G_CPP_ID=$(gz_process_in "config_load" "G_CPP_ID")
G_CPP_PATH=$(gz_process_in "config_load" "G_CPP_PATH")
G_CPP_NAME=$(gz_process_in "config_load" "G_CPP_NAME")
G_QT_PATH=$(gz_process_in "config_load" "G_QT_PATH")
G_QT_NAME=$(gz_process_in "config_load" "G_QT_NAME")
G_STATE="S_METHOD"
}
#================================================
GCpp_QUIT() {
echo
read -p "QUIT (Oui/[N]on) ? " lAnswer
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "o" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "n" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "" ] ; then G_STATE="S_INIT"
fi
}
#================================================
GCpp_Main
#================================================
cd $GPWD
#================================================
