#!/bin/bash
#================================================
GPWD=$PWD
#================================================
. $GPATH/.config
#================================================
lCheckIn="GPATH" ; if [ "${!lCheckIn}" = "" ] || ! [ -d "${!lCheckIn}" ] ; then echo $(gz_color s "$lCheckIn ?" yellow fg) ; exit ; fi 
lCheckIn="GDEV_PATH" ; if [ "${!lCheckIn}" = "" ] || ! [ -d "${!lCheckIn}" ] ; then echo $(gz_color s "$lCheckIn ?" yellow fg) ; exit ; fi 
#================================================
GDev_main() {
lArgSize="$#"
if [ "$lArgSize" = "0" ] ; then GDev_help "$@"
else GDev_process "$@" ; fi
}
#================================================
GDev_help() {
lScript=$(gz_string filename "$0")
GSCRIPT="\t\033[0;35m${lScript}\033[0m"
GCOMMENT="\033[0;33m%s\033[0m"
GHELP="$GSCRIPT : $GCOMMENT\n"
GREQUEST="\033[36m%s\033[0m"
GPROCESS="$GSCRIPT $GREQUEST : $GCOMMENT\n"
printf "\n"
printf "%s\n" "Description:"
printf "\t%s\n" "Operations sur le dossier ReadyDev."
printf "\n"
printf "%s\n" "Utilisation:"
printf "$GHELP" "afficher aide"
printf "$GPROCESS" "git_pa" "ajouter commiter valider modifications git"
printf "$GPROCESS" "git_pu" "tirer modifications git"
printf "\n"
}
#================================================
GDev_process() {
lArgSize="$#"
lArgCount=1
lRunFlag=0
while [ 1 ] ; do
if [ "$lArgCount" -gt "$lArgSize" ] ; then break ; fi
lKey=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
# git_pa
if [ "$lKey" = "git_pa" ] ; then 
GDev_git_push_all ; lRunFlag=1
# git_pu
elif [ "$lKey" = "git_pu" ] ; then 
GDev_git_pull ; lRunFlag=1
#
fi
done
if [ "$lRunFlag" = "0" ] ; then GDev_help ; fi 
}
#================================================
GDev_git_push_all() {
cd $GDEV_PATH
git add --all
git commit -m "Initial Commit"
git push -u origin master
cd $GPWD
}
#================================================
GDev_git_pull() {
cd $GDEV_PATH
git pull
cd $GPWD
}
#================================================
GDev_main "$@"
#================================================
