#!/bin/bash
#================================================
GPWD=$PWD
#================================================
lCheckIn="GPATH" ; if [ "${!lCheckIn}" = "" ] || ! [ -d "${!lCheckIn}" ] ; then echo "ERREUR : ${lCheckIn} ?" ; exit ; fi 
#================================================
. $GPATH/.config
#================================================
lCheckIn="GGIT_ROOT" ; if [ "${!lCheckIn}" = "" ] ; then echo "ERREUR : ${lCheckIn} ?" ; exit ; fi 
lCheckIn="GGIT_REPO" ; if [ "${!lCheckIn}" = "" ] ; then echo "ERREUR : ${lCheckIn} ?" ; exit ; fi 
#================================================
lGitUrl="https://github.com/gkesse/${GGIT_REPO}.git"
#================================================
# Configurations
printf "\n"
printf "Configurations :\n"
printf "\t%-20s : %s\n" "GGIT_ROOT" "$GGIT_ROOT"
printf "\t%-20s : %s\n" "GGIT_REPO" "$GGIT_REPO"
printf "\t%-20s : %s\n" "git_url" "$lGitUrl"
printf "\n"
#================================================
read -p "Confirmation de continuer (Oui|[N]on) ? " lAnswer
case $lAnswer in
    [Oo]* ) echo "OUI : operation effectuee" ; echo ;;
    * ) echo "NON : operation annulee" ; echo ; exit ;;
esac
#================================================
cd $GGIT_ROOT
sudo git clone $lGitUrl
#================================================
cd $GPWD
#================================================
