#!/bin/bash
#================================================
GPWD=$PWD
#================================================
lCheckIn="GPATH" ; if [ "${!lCheckIn}" = "" ] || ! [ -d "${!lCheckIn}" ] ; then echo "ERREUR : ${lCheckIn} ?" ; exit ; fi 
#================================================
. $GPATH/.config
#================================================
lCheckIn="GGIT_ROOT" ; if [ "${!lCheckIn}" = "" ] ; then echo "ERREUR : ${lCheckIn} ?" ; exit ; fi 
#================================================
lArgIn="$1" ; lArgName="nom_projet" ; if [ -z "${lArgIn}" ] ; then echo "ERREUR : ${lArgName} ?" ; exit ; fi
#================================================
lProjectName=$1
#================================================
lGitUrl="https://github.com/gkesse/${lProjectName}.git"
#================================================
# Configurations
printf "\n"
printf "Configurations :\n"
printf "\t%-20s : %s\n" "GGIT_ROOT" "$GGIT_ROOT"
printf "\t%-20s : %s\n" "nom_projet" "$lProjectName"
printf "\t%-20s : %s\n" "git_url" "$lGitUrl"
printf "\n"
#================================================
read -p "Confirmation de continuer (Oui|[N]on) ? " lAnswer
case $lAnswer in
    [Oo]* ) echo "OUI : operation effectuee" ; echo ;;
    * ) echo "NON : operation annulee" ; echo ; exit ;;
esac
#================================================
cd $GGIT_ROOT
sudo git clone $lGitUrl
#================================================
cd $GPWD
#================================================
