#!/bin/bash
#================================================
GPWD=$PWD
#================================================
G_STATE="S_INIT"
#================================================
. $GPATH/.env
#================================================
GPython_Main() {
while [ 1 ] ; do
case "$G_STATE" in 
    "S_ADMIN") GPython_ADMIN ;;
    "S_INIT") GPython_INIT ;;
    "S_METHOD") GPython_METHOD ;;
    "S_CHOICE") GPython_CHOICE ;;
    #
    "S_PYTHON_COMPILE_PYTHON_PATH") GPython_PYTHON_COMPILE_PYTHON_PATH ;;
    "S_PYTHON_COMPILE_PYTHON_NAME") GPython_PYTHON_COMPILE_PYTHON_NAME ;;
    "S_PYTHON_COMPILE") GPython_PYTHON_COMPILE ;;
    #
    "S_PIP_LIST") GPython_PIP_LIST ;;
    #
    "S_PIP_INSTALL_PACKAGE_NAME") GPython_PIP_INSTALL_PACKAGE_NAME ;;
    "S_PIP_INSTALL") GPython_PIP_INSTALL ;;
    #
    "S_PIP_UNINSTALL_PACKAGE_NAME") GPython_PIP_UNINSTALL_PACKAGE_NAME ;;
    "S_PIP_UNINSTALL") GPython_PIP_UNINSTALL ;;
    #
    "S_SAVE") GPython_SAVE ;;
    "S_LOAD") GPython_LOAD ;;
    "S_QUIT") GPython_QUIT ;;
    *) break ;;
esac    
done
}
#================================================
GPython_ADMIN() {
gz_admin
G_STATE="S_END"
}
#================================================
GPython_INIT() {
printf "\n"
printf "PYTHON !!!\n"
printf "\t%-2s : %s\n" "-q" "quitter l'application"
printf "\t%-2s : %s\n" "-i" "reinitialiser l'application"
printf "\t%-2s : %s\n" "-a" "redemarrer l'administration"
printf "\t%-2s : %s\n" "-v" "valider les configurations"
printf "\n"
G_STATE="S_LOAD"
}
#================================================
GPython_METHOD() {
printf "PYTHON :\n"
printf "\t%-2s : %s\n" "1" "compiler le projet"
printf "\n"
printf "\t%-2s : %s\n" "10" "lister les packages PIP"
printf "\t%-2s : %s\n" "11" "installer un package PIP"
printf "\t%-2s : %s\n" "12" "desinstaller un package PIP"
printf "\n"
G_STATE="S_CHOICE"
}
#================================================
GPython_CHOICE() {
read -p "PYTHON ($G_PYTHON_ID) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_PYTHON_ID" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
#
elif [ "$lAnswer" = "1" ] ; then G_STATE="S_PYTHON_COMPILE_PYTHON_PATH" ; G_PYTHON_ID="$lAnswer"
#
elif [ "$lAnswer" = "10" ] ; then G_STATE="S_PIP_LIST" ; G_PYTHON_ID="$lAnswer"
elif [ "$lAnswer" = "11" ] ; then G_STATE="S_PIP_INSTALL_PACKAGE_NAME" ; G_PYTHON_ID="$lAnswer"
elif [ "$lAnswer" = "12" ] ; then G_STATE="S_PIP_UNINSTALL_PACKAGE_NAME" ; G_PYTHON_ID="$lAnswer"
#
fi
}
#================================================
GPython_PIP_LIST() {
echo
sudo pip2 freeze
G_STATE="S_SAVE"
}
#================================================
GPython_PIP_INSTALL_PACKAGE_NAME() {
read -p "G_PACKAGE_NAME ($G_PACKAGE_NAME) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_PACKAGE_NAME" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "-v" ] ; then G_STATE="S_PIP_INSTALL"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_PIP_INSTALL" ; G_PACKAGE_NAME="$lAnswer"
fi
}
#================================================
GPython_PIP_INSTALL() {
echo
sudo pip2 install $G_PACKAGE_NAME
G_STATE="S_SAVE"
}
#================================================
GPython_PIP_UNINSTALL_PACKAGE_NAME() {
read -p "G_PACKAGE_NAME ($G_PACKAGE_NAME) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_PACKAGE_NAME" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "-v" ] ; then G_STATE="S_PIP_UNINSTALL"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_PIP_UNINSTALL" ; G_PACKAGE_NAME="$lAnswer"
fi
}
#================================================
GPython_PIP_UNINSTALL() {
echo
sudo pip2 uninstall $G_PACKAGE_NAME
G_STATE="S_SAVE"
}
#================================================
GPython_PYTHON_COMPILE_PYTHON_PATH() {
read -p "G_PYTHON_PATH ($G_PYTHON_PATH) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_PYTHON_PATH" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "-v" ] ; then G_STATE="S_PYTHON_COMPILE"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_PYTHON_COMPILE_PYTHON_NAME" ; G_PYTHON_PATH="$lAnswer"
fi
}
#================================================
GPython_PYTHON_COMPILE_PYTHON_NAME() {
read -p "G_PYTHON_NAME ($G_PYTHON_NAME) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_PYTHON_NAME" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "-v" ] ; then G_STATE="S_PYTHON_COMPILE"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_PYTHON_COMPILE" ; G_PYTHON_NAME="$lAnswer"
fi
}
#================================================
GPython_PYTHON_COMPILE() {
echo
lBuldPath="$G_PYTHON_PATH/$G_PYTHON_NAME/unix"
lMakefile="Makefile.python"
cd $lBuldPath
make -f "$lMakefile" all
G_STATE="S_SAVE"
}
#================================================
GPython_SAVE() {
gz_process_in "config_save" "G_PYTHON_ID" "$G_PYTHON_ID"
gz_process_in "config_save" "G_PYTHON_PATH" "$G_PYTHON_PATH"
gz_process_in "config_save" "G_PYTHON_NAME" "$G_PYTHON_NAME"
gz_process_in "config_save" "G_PACKAGE_NAME" "$G_PACKAGE_NAME"
G_STATE="S_QUIT"
}
#================================================
GPython_LOAD() {
G_PYTHON_ID=$(gz_process_in "config_load" "G_PYTHON_ID")
G_PYTHON_PATH=$(gz_process_in "config_load" "G_PYTHON_PATH")
G_PYTHON_NAME=$(gz_process_in "config_load" "G_PYTHON_NAME")
G_PACKAGE_NAME=$(gz_process_in "config_load" "G_PACKAGE_NAME")
G_STATE="S_METHOD"
}
#================================================
GPython_QUIT() {
echo
read -p "QUIT (Oui/[N]on) ? " lAnswer
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "o" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "n" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "" ] ; then G_STATE="S_INIT"
fi
}
#================================================
GPython_Main
#================================================
cd $GPWD
#================================================
