#!/bin/bash
#================================================
GPWD=$PWD
#================================================
G_STATE="S_INIT"
#================================================
GPhp_Main() {
while [ 1 ] ; do
case "$G_STATE" in 
    "S_ADMIN") GPhp_ADMIN ;;
    "S_INIT") GPhp_INIT ;;
    "S_METHOD") GPhp_METHOD ;;
    "S_CHOICE") GPhp_CHOICE ;;
    #

    #
    "S_SAVE") GPhp_SAVE ;;
    "S_LOAD") GPhp_LOAD ;;
    "S_QUIT") GPhp_QUIT ;;
    *) break ;;
esac    
done
}
#================================================
GPhp_ADMIN() {
gz_admin
G_STATE="S_END"
}
#================================================
GPhp_INIT() {
printf "\n"
printf "PHP !!!\n"
printf "\t%2s : %s\n" "-q" "quitter l'application"
printf "\t%2s : %s\n" "-i" "reinitialiser l'application"
printf "\t%2s : %s\n" "-a" "redemarrer l'administration"
printf "\t%2s : %s\n" "-v" "valider les configurations"
printf "\n"
G_STATE="S_LOAD"
}
#================================================
GPhp_METHOD() {
printf "PHP :\n"
printf "\t%2s : %s\n" "1" "creer la table"
printf "\n"
G_STATE="S_CHOICE"
}
#================================================
GPhp_CHOICE() {
read -p "PHP ($G_PHP_ID) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_PHP_ID" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
#
elif [ "$lAnswer" = "1" ] ; then G_STATE="S_CREATE_READYDEV_DB" ; G_PHP_ID="$lAnswer"
fi
}
#================================================
GPhp_DELETE_READYDEV_DB() {
read -p "G_READYDEV_DB ($G_READYDEV_DB) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_READYDEV_DB" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_DELETE_VIEW_KEY" ; G_READYDEV_DB="$lAnswer"
fi
}
#================================================
GPhp_SAVE() {
gz_process_in "config_save" "G_PHP_ID" "$G_PHP_ID"
G_STATE="S_QUIT"
}
#================================================
GPhp_LOAD() {
G_PHP_ID=$(gz_process_in "config_load" "G_PHP_ID")
G_STATE="S_METHOD"
}
#================================================
GPhp_QUIT() {
echo
read -p "PHP_QUIT (Oui/[N]on) ? " lAnswer
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "o" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "n" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "" ] ; then G_STATE="S_INIT"
fi
}
#================================================
GPhp_Main
#================================================
cd $GPWD
#================================================
