#!/bin/bash
#================================================
GPWD=$PWD
#================================================
G_STATE="S_INIT"
#================================================
GPhp_Main() {
while [ 1 ] ; do
case "$G_STATE" in 
    "S_ADMIN") GPhp_ADMIN ;;
    "S_INIT") GPhp_INIT ;;
    "S_METHOD") GPhp_METHOD ;;
    "S_CHOICE") GPhp_CHOICE ;;
    #

    #
    "S_SAVE") GPhp_SAVE ;;
    "S_LOAD") GPhp_LOAD ;;
    *) break ;;
esac    
done
}
#================================================
GPhp_ADMIN() {
gz_admin
G_STATE="S_SAVE"
}
#================================================
GPhp_INIT() {
printf "\n"
printf "### VIEWS ###\n"
printf "\t%2s : %s\n" "-q" "quitter l'application"
printf "\t%2s : %s\n" "-i" "reinitialiser l'application"
printf "\t%2s : %s\n" "-a" "redemarrer l'administration"
printf "\n"
G_STATE="S_LOAD"
}
#================================================
GPhp_METHOD() {
printf "VIEWS :\n"
printf "\t%2s : %s\n" "1" "creer la table"
printf "\n"
G_STATE="S_CHOICE"
}
#================================================
GPhp_CHOICE() {
read -p "VIEWS ($G_PHP_ID) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_PHP_ID" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
#
elif [ "$lAnswer" = "1" ] ; then G_STATE="S_CREATE_READYDEV_DB" ; G_PHP_ID="$lAnswer"
fi
}
#================================================
GPhp_DELETE_READYDEV_DB() {
read -p "G_READYDEV_DB ($G_READYDEV_DB) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_READYDEV_DB" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_DELETE_VIEW_KEY" ; G_READYDEV_DB="$lAnswer"
fi
}
#================================================
GPhp_SAVE() {
gz_config_edit_in "G_PHP_ID" "$G_PHP_ID"
G_STATE="S_END"
}
#================================================
GPhp_LOAD() {
G_PHP_ID=$(gz_config_read_in "G_PHP_ID")
G_STATE="S_METHOD"
}
#================================================
GPhp_Main
#================================================
cd $GPWD
#================================================
