#!/bin/bash
#================================================
GPWD=$PWD
#================================================
G_STATE="S_INIT"
#================================================
GPacman_Main() {
while [ 1 ] ; do
case "$G_STATE" in 
    "S_ADMIN") GPacman_ADMIN ;;
    "S_INIT") GPacman_INIT ;;
    "S_METHOD") GPacman_METHOD ;;
    "S_CHOICE") GPacman_CHOICE ;;
    #
    "S_SEARCH_PACKAGE_NAME") GPacman_SEARCH_PACKAGE_NAME ;;
    "S_SEARCH") GPacman_SEARCH ;;
    #
    "S_UPDATE") GPacman_UPDATE ;;
    #
    "S_INSTALL_PACKAGE_NAME") GPacman_INSTALL_PACKAGE_NAME ;;
    "S_INSTALL") GPacman_INSTALL ;;
    #
    "S_SAVE") GPacman_SAVE ;;
    "S_LOAD") GPacman_LOAD ;;
    *) break ;;
esac    
done
}
#================================================
GPacman_ADMIN() {
gz_admin
G_STATE="S_SAVE"
}
#================================================
GPacman_INIT() {
printf "\n"
printf "### PACMAN ###\n"
printf "\t%2s : %s\n" "-q" "quitter l'application"
printf "\t%2s : %s\n" "-i" "reinitialiser l'application"
printf "\t%2s : %s\n" "-a" "redemarrer l'administration"
printf "\n"
G_STATE="S_LOAD"
}
#================================================
GPacman_METHOD() {
printf "PACMAN :\n"
printf "\t%2s : %s\n" "1" "rechercher un package"
printf "\t%2s : %s\n" "2" "mettre a jour le systeme"
printf "\t%2s : %s\n" "3" "installer un package"
printf "\t%2s : %s\n" "4" "debloquer le systeme"
printf "\n"
G_STATE="S_CHOICE"
}
#================================================
GPacman_CHOICE() {
read -p "PACMAN ($G_PACMAN_ID) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_PACMAN_ID" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
#
elif [ "$lAnswer" = "1" ] ; then G_STATE="S_SEARCH_PACKAGE_NAME" ; G_PACMAN_ID="$lAnswer"
elif [ "$lAnswer" = "2" ] ; then G_STATE="S_UPDATE" ; G_PACMAN_ID="$lAnswer"
elif [ "$lAnswer" = "3" ] ; then G_STATE="S_INSTALL_PACKAGE_NAME" ; G_PACMAN_ID="$lAnswer"
elif [ "$lAnswer" = "4" ] ; then G_STATE="S_UNLOCK" ; G_PACMAN_ID="$lAnswer"
fi
}
#================================================
GPacman_UNLOCK() {
if [ -f "$G_UNLOCK_FILE" ] ; then rm -f $G_UNLOCK_FILE ; fi
G_STATE="S_SAVE"
}
#================================================
GPacman_INSTALL_PACKAGE_NAME() {
read -p "G_PACKAGE_NAME ($G_PACKAGE_NAME) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_PACKAGE_NAME" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_INSTALL" ; G_PACKAGE_NAME="$lAnswer"
fi
}
#================================================
GPacman_INSTALL() {
echo
pacman -S "$G_PACKAGE_NAME"
G_STATE="S_SAVE"
echo
}
#================================================
GPacman_UPDATE() {
echo
pacman -Syu
G_STATE="S_SAVE"
echo
}
#================================================
GPacman_SEARCH_PACKAGE_NAME() {
read -p "G_PACKAGE_NAME ($G_PACKAGE_NAME) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_PACKAGE_NAME" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_SEARCH" ; G_PACKAGE_NAME="$lAnswer"
fi
}
#================================================
GPacman_SEARCH() {
echo
pacman -Ss --needed "$G_PACKAGE_NAME"
G_STATE="S_SAVE"
echo
}
#================================================
GPacman_SAVE() {
gz_config_edit_in "G_PACMAN_ID" "$G_PACMAN_ID"
gz_config_edit_in "G_PACKAGE_NAME" "$G_PACKAGE_NAME"
G_STATE="S_END"
}
#================================================
GPacman_LOAD() {
G_PACMAN_ID=$(gz_config_read_in "G_PACMAN_ID")
G_PACKAGE_NAME=$(gz_config_read_in "G_PACKAGE_NAME")
G_STATE="S_METHOD"
}
#================================================
GPacman_Main
#================================================
cd $GPWD
#================================================
