#!/bin/bash
#================================================
GPWD=$PWD
#================================================
G_STATE="S_INIT"
#================================================
G_CONFIG_DB="$GPATH/.CONFIG_O.dat"
#================================================
GSQLite_Main() {
while [ 1 ] ; do
case "$G_STATE" in 
    "S_ADMIN") GSQLite_ADMIN ;;
    "S_INIT") GSQLite_INIT ;;
    "S_METHOD") GSQLite_METHOD ;;
    "S_CHOICE") GSQLite_CHOICE ;;
    #
    "S_VERSION") GSQLite_VERSION ;;
    "S_CONFIG_DATA_CREATE") GSQLite_CONFIG_DATA_CREATE ;;
    #
    "S_SAVE") GSQLite_SAVE ;;
    "S_LOAD") GSQLite_LOAD ;;
    "S_QUIT") GSQLite_QUIT ;;
    *) break ;;
esac    
done
}
#================================================
GSQLite_ADMIN() {
gz_admin
G_STATE="S_END"
}
#================================================
GSQLite_INIT() {
printf "\n"
printf "SQLITE !!!\n"
printf "\t%2s : %s\n" "-q" "quitter l'application"
printf "\t%2s : %s\n" "-i" "reinitialiser l'application"
printf "\t%2s : %s\n" "-a" "redemarrer l'administration"
printf "\t%2s : %s\n" "-v" "valider les configurations"
printf "\n"
G_STATE="S_LOAD"
}
#================================================
GSQLite_METHOD() {
printf "SQLITE :\n"
printf "\t%2s : %s\n" "1" "afficher la version"
printf "\t%2s : %s\n" "2" "creer la table CONFIG_DATA"
printf "\n"
G_STATE="S_CHOICE"
}
#================================================
GSQLite_CHOICE() {
read -p "SQLITE ($G_SQLITE_ID) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_SQLITE_ID" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
#
elif [ "$lAnswer" = "1" ] ; then G_STATE="S_VERSION" ; G_SQLITE_ID="$lAnswer"
elif [ "$lAnswer" = "2" ] ; then G_STATE="S_CONFIG_DATA_CREATE" ; G_SQLITE_ID="$lAnswer"
fi
}
#================================================
GSQLite_CONFIG_DATA_CREATE() {
echo
gz_process_in "sqlite_query" "$G_CONFIG_DB" "
create table CONFIG_DATA(
CONFIG_KEY text unique not null,
CONFIG_VALUE text
)
"
G_STATE="S_SAVE"
}
#================================================
GSQLite_VERSION() {
echo
sqlite3 --version
G_STATE="S_SAVE"
}
#================================================
GSQLite_SAVE() {
gz_process_in "config_save" "G_SQLITE_ID" "$G_SQLITE_ID"
G_STATE="S_QUIT"
}
#================================================
GSQLite_LOAD() {
G_SQLITE_ID=$(gz_process_in "config_load" "G_SQLITE_ID")
G_STATE="S_METHOD"
}
#================================================
GSQLite_QUIT() {
echo
read -p "QUIT (Oui/[N]on) ? " lAnswer
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "o" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "n" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "" ] ; then G_STATE="S_INIT"
fi
}
#================================================
GSQLite_Main
#================================================
cd $GPWD
#================================================
