#!/bin/bash
#================================================
GPWD=$PWD
#================================================
G_STATE="S_INIT"
#================================================
. $GPATH/env
#================================================
GShell_Main() {
while [ 1 ] ; do
case "$G_STATE" in 
    "S_ADMIN") GShell_ADMIN ;;
    "S_INIT") GShell_INIT ;;
    "S_METHOD") GShell_METHOD ;;
    "S_CHOICE") GShell_CHOICE ;;
    #
    "S_CMD_RUN_CMD_TEXT") GShell_CMD_RUN_CMD_TEXT ;;
    "S_CMD_RUN") GShell_CMD_RUN ;; 
    #
    "S_SAVE") GShell_SAVE ;;
    "S_LOAD") GShell_LOAD ;;
    "S_QUIT") GShell_QUIT ;;
    *) break ;;
esac    
done
}
#================================================
GShell_ADMIN() {
gz_admin
G_STATE="S_END"
}
#================================================
GShell_INIT() {
printf "\n"
printf "SHELL !!!\n"
printf "\t%2s : %s\n" "-q" "quitter l'application"
printf "\t%2s : %s\n" "-i" "reinitialiser l'application"
printf "\t%2s : %s\n" "-a" "redemarrer l'administration"
printf "\t%2s : %s\n" "-v" "valider les configurations"
printf "\n"
G_STATE="S_LOAD"
}
#================================================
GShell_METHOD() {
printf "SHELL :\n"
printf "\t%2s : %s\n" "1" "executer une commande SHELL"
printf "\n"
G_STATE="S_CHOICE"
}
#================================================
GShell_CHOICE() {
read -p "SHELL ($G_SHELL_ID) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_SHELL_ID" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
#
elif [ "$lAnswer" = "1" ] ; then G_STATE="S_CMD_RUN_CMD_TEXT" ; G_SHELL_ID="$lAnswer"
#
fi
}
#================================================
GShell_CMD_RUN_CMD_TEXT() {
read -p "G_CMD_TEXT ($G_CMD_TEXT) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_CMD_TEXT" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "-v" ] ; then G_STATE="S_CMD_RUN"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_CMD_RUN" ; G_CMD_TEXT="$lAnswer"
fi
}
#================================================
GShell_CMD_RUN() {
echo
echo "$G_CMD_TEXT"
echo
$G_CMD_TEXT
G_STATE="S_SAVE"
}
#================================================
GShell_SAVE() {
gz_process_in "config_save" "G_SHELL_ID" "$G_SHELL_ID"
gz_process_in "config_save" "G_CMD_TEXT" "$G_CMD_TEXT"
G_STATE="S_QUIT"
}
#================================================
GShell_LOAD() {
G_SHELL_ID=$(gz_process_in "config_load" "G_SHELL_ID")
G_CMD_TEXT=$(gz_process_in "config_load" "G_CMD_TEXT")
G_STATE="S_METHOD"
}
#================================================
GShell_QUIT() {
echo
read -p "QUIT (Oui/[N]on) ? " lAnswer
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "o" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "n" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "" ] ; then G_STATE="S_INIT"
fi
}
#================================================
GShell_Main
#================================================
cd $GPWD
#================================================

