#!/bin/bash
#================================================
GPWD=$PWD
#================================================
G_STATE="S_INIT"
#================================================
GSQLite_Main() {
while [ 1 ] ; do
case "$G_STATE" in 
    "S_ADMIN") GSQLite_ADMIN ;;
    "S_INIT") GSQLite_INIT ;;
    "S_METHOD") GSQLite_METHOD ;;
    "S_CHOICE") GSQLite_CHOICE ;;
    #
    "S_VERSION") GSQLite_VERSION ;;
    #
    "S_SAVE") GSQLite_SAVE ;;
    "S_LOAD") GSQLite_LOAD ;;
    *) break ;;
esac    
done
}
#================================================
GSQLite_ADMIN() {
gz_admin
G_STATE="S_SAVE"
}
#================================================
GSQLite_INIT() {
printf "\n"
printf "### SQLITE ###\n"
printf "\t%2s : %s\n" "-q" "quitter l'application"
printf "\t%2s : %s\n" "-i" "reinitialiser l'application"
printf "\t%2s : %s\n" "-a" "redemarrer l'administration"
printf "\n"
G_STATE="S_LOAD"
}
#================================================
GSQLite_METHOD() {
printf "SQLITE :\n"
printf "\t%2s : %s\n" "1" "afficher la version"
printf "\n"
G_STATE="S_CHOICE"
}
#================================================
GSQLite_CHOICE() {
read -p "SQLITE ($G_SQLITE_ID) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_SQLITE_ID" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
#
elif [ "$lAnswer" = "1" ] ; then G_STATE="S_VERSION" ; G_SQLITE_ID="$lAnswer"
fi
}
#================================================
GSQLite_VERSION() {
echo
sqlite3 --version
G_STATE="S_SAVE"
echo
}
#================================================
GSQLite_SAVE() {
gz_config_edit_in "G_SQLITE_ID" "$G_SQLITE_ID"
G_STATE="S_END"
}
#================================================
GSQLite_LOAD() {
G_SQLITE_ID=$(gz_config_read_in "G_SQLITE_ID")
G_STATE="S_METHOD"
}
#================================================
GSQLite_Main
#================================================
cd $GPWD
#================================================
