#!/bin/bash
#================================================
GPWD=$PWD
#================================================
GPATH=$(gz_pwd)
GTMP_PATH=$GPATH/tmp ; if ! [ -d "$GTMP_PATH" ] ; then mkdir $GTMP_PATH ; fi
GTMP_FILE_N1=$GTMP_PATH/tmp_file_n1.txt
#================================================
if ! [[ -z "$GDATABASE_ROOT" ]] ; then
export GDATABASE_ROOT=/cygdrive/c/Users/Admin/Downloads/Programs/ReadyShop/data/sqlite
fi
GDATABASE_NAME=test.dat
GDATABASE_PATH=$GDATABASE_ROOT/$GDATABASE_NAME
#================================================
GSQLite_main() {
lArgSize="$#"
if [ "$lArgSize" = "0" ] ; then GSQLite_help "$@"
else GSQLite_process "$@" ; fi
}
#================================================
GSQLite_help() {
lScript=$(gz_string filename "$0")
GSCRIPT="\t\033[0;35m${lScript}\033[0m"
GCOMMENT="\033[0;33m%s\033[0m"
GHELP="$GSCRIPT : $GCOMMENT\n"
GREQUEST="\033[36m%s\033[0m"
GPROCESS="$GSCRIPT $GREQUEST : $GCOMMENT\n"
printf "\n"
printf "%s\n" "Description:"
printf "\t%s\n" "Operations sur les chaines de caracteres."
printf "\n"
printf "%s\n" "Utilisation:"
printf "$GHELP" "afficher aide"
printf "$GPROCESS" "query <sql_in>" "executer requete sql"
printf "$GPROCESS" "clone_t <table_in> <table_out> <column_in>" "cloner table"
printf "$GPROCESS" "rename_t <table_in> <table_out>" "renommer table"
printf "$GPROCESS" "drop_t <table_in>" "supprimer table"
printf "$GPROCESS" "add_c <table_in> <column_in>" "ajouter colonne"
printf "$GPROCESS" "drop_c <table_in> <column_in>" "supprimer colonne"
printf "$GPROCESS" "remove_c <table_in> <column_in>" "supprimer colonne"
printf "$GPROCESS" "alter_c <table_in> <column_in>" "modifier colonne"
printf "$GPROCESS" "modify_c <table_in> <column_in>" "modifier colonne"
printf "$GPROCESS" "list_c <table_in> <column_in>" "lister colonne"
printf "$GPROCESS" "schema <table_in>" "schematiser table"
printf "$GPROCESS" "set_r <path_in>" "initialiser racine"
printf "$GPROCESS" "set_n <name_in>" "initialiser nom base de donnees"
printf "$GPROCESS" "set_p <path_in>" "initialiser chemin"
printf "$GPROCESS" "get_p" "recuperer chemin"
printf "\n"
}
#================================================
GSQLite_process() {
lArgSize="$#"
lArgCount=1
lRunFlag=0
while [ 1 ] ; do
if [ "$lArgCount" -gt "$lArgSize" ] ; then break ; fi
lKey=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
# query
if [ "$lKey" = "query" ] ; then 
lQuery=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
GSQLite_query "$lQuery" ; lRunFlag=1
# users_c
elif [ "$lKey" = "users_c" ] ; then 
GSQLite_users_create ; lRunFlag=1
# users_d
elif [ "$lKey" = "users_d" ] ; then 
GSQLite_users_drop ; lRunFlag=1
# users_dl
elif [ "$lKey" = "users_dl" ] ; then 
lId=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
GSQLite_users_delete "$lId" ; lRunFlag=1
# users_i
elif [ "$lKey" = "users_i" ] ; then 
lRow=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
GSQLite_users_insert "$lRow" ; lRunFlag=1
# users_s
elif [ "$lKey" = "users_s" ] ; then 
GSQLite_users_select ; lRunFlag=1
# users_u
elif [ "$lKey" = "users_u" ] ; then 
lId=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
lPassword=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
GSQLite_users_update "$lId" "$lPassword" ; lRunFlag=1
# show_t
elif [ "$lKey" = "show_t" ] ; then 
GSQLite_show_tables ; lRunFlag=1
# schema
elif [ "$lKey" = "schema" ] ; then 
GSQLite_schema ; lRunFlag=1
# clone_t
elif [ "$lKey" = "clone_t" ] ; then 
lTableIn=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
lTableOut=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
lColumn=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
GSQLite_clone_table "$lTableIn" "$lTableOut" "$lColumn" ; lRunFlag=1
# rename_t
elif [ "$lKey" = "rename_t" ] ; then 
lTableIn=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
lTableOut=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
GSQLite_rename_table "$lTableIn" "$lTableOut" ; lRunFlag=1
# drop_t
elif [ "$lKey" = "drop_t" ] ; then 
lTable=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
GSQLite_drop_table "$lTable" ; lRunFlag=1
# add_c 
elif [ "$lKey" = "add_c" ] ; then 
lTable=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
lColumn=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
GSQLite_add_column "$lTable" "$lColumn" ; lRunFlag=1
# drop_c
elif [ "$lKey" = "drop_c" ] ; then 
lTable=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
lColumn=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
GSQLite_drop_column "$lTable" "$lColumn" ; lRunFlag=1
# remove_c
elif [ "$lKey" = "remove_c" ] ; then 
lTable=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
lColumn=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
GSQLite_remove_column "$lTable" "$lColumn" ; lRunFlag=1
# alter_c
elif [ "$lKey" = "alter_c" ] ; then 
lTable=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
lColumn=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
GSQLite_alter_column "$lTable" "$lColumn" ; lRunFlag=1
# modify_c
elif [ "$lKey" = "modify_c" ] ; then 
lTable=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
lColumn=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
GSQLite_modify_column "$lTable" "$lColumn" ; lRunFlag=1
# list_c
elif [ "$lKey" = "list_c" ] ; then 
lTable=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
lRemove=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
GSQLite_list_column "$lTable" "$lRemove" ; lRunFlag=1
# set_r
elif [ "$lKey" = "set_r" ] ; then 
lPath=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
GSQLite_set_root "$lPath" ; lRunFlag=1
# set_n
elif [ "$lKey" = "set_n" ] ; then 
lName=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
GSQLite_set_name "$lName" ; lRunFlag=1
# set_p
elif [ "$lKey" = "set_p" ] ; then 
lPath=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
GSQLite_set_path "$lPath" ; lRunFlag=1
# get_p
elif [ "$lKey" = "get_p" ] ; then 
GSQLite_get_path ; lRunFlag=1
#
fi
done
if [ "$lRunFlag" = "0" ] ; then GSQLite_help ; fi
}
#================================================
GSQLite_query() {
local lQuery=$1
sqlite3 $GDATABASE_PATH << _EOF_
$lQuery
.exit
_EOF_
}
#================================================
GSQLite_users_create() {
GSQLite_query "
create table users(
id integer primary key autoincrement not null,
email text,
password text);"
}
#================================================
GSQLite_users_drop() {
GSQLite_query "drop table users;"
}
#================================================
GSQLite_users_insert() {
local lRow=$1
lEmail=$(gz_string split "$lRow" "|" 1)
lPassword=$(gz_string split "$lRow" "|" 2)
lPassword=$(gz_md5 h "$lEmail|$lPassword")
lExist=$(GSQLite_users_email_exist "$lEmail")
if [ "$lExist" = "1" ] ; then gz_color s "cet email existe deja" yellow fg ; return ; fi
GSQLite_query "insert into users
(email,password) 
values ('$lEmail','$lPassword');"
}
#================================================
GSQLite_users_delete() {
local lId=$1
if [ "$lId" = "" ] ; then gz_color s "id ?" yellow fg ; return ; fi
GSQLite_query "delete from users where id = $lId;"
}
#================================================
GSQLite_users_update() {
local lId=$1
local lPassword=$2
if [ "$lId" = "" ] ; then gz_color s "id ?" yellow fg ; return ; fi
if [ "$lPassword" = "" ] ; then gz_color s "password ?" yellow fg ; return ; fi
lEmail=$(GSQLite_query "select * from users where id = $lId;" | awk -F "|" '{print $2 ; exit}')
lPassword=$(gz_md5 h "$lEmail|$lPassword")
GSQLite_query "update users 
set password = '$lPassword'
where id = $lId;"
}
#================================================
GSQLite_users_select() {
GSQLite_query "select * from users;"
}
#================================================
GSQLite_users_select_id() {
local lId=$1
if [ "$lId" = "" ] ; then gz_color s "id ?" yellow fg ; return ; fi
lWhere="where id = $lId"
GSQLite_query "select * from users $lWhere;"
}
#================================================
GSQLite_users_email_exist() {
local lEmail=$1
lResult=$(GSQLite_query "select exists(select 1 from users where email='$lEmail' limit 1);")
lExist=0
if [[ "$lResult" = *"1"* ]] ; then lExist=1 ; fi
echo "$lExist"
}
#================================================
GSQLite_show_tables() {
GSQLite_query ".tables"
}
#================================================
GSQLite_schema() {
GSQLite_query ".schema"
}
#================================================
GSQLite_clone_table() {
local lTableIn=$1
local lTableOut=$2
local lColumn=$3
lQuery="create table $lTableOut AS select $lColumn from $lTableIn;"
GSQLite_query "$lQuery"
}
#================================================
GSQLite_rename_table() {
local lTableIn=$1
local lTableOut=$2
lQuery="alter table $lTableIn rename to $lTableOut;"
GSQLite_query "$lQuery"
}
#================================================
GSQLite_drop_table() {
local lTable=$1
lQuery="drop table $lTable;"
GSQLite_query "$lQuery"
}
#================================================
GSQLite_add_column() {
local lTable=$1
local lColumn=$2
lQuery="alter table $lTable add $lColumn;"
GSQLite_query "$lQuery"
}
#================================================
GSQLite_drop_column() {
local lTable=$1
local lColumn=$2
lQuery="alter table $lTable drop column $lColumn;"
GSQLite_query "$lQuery"
}
#================================================
GSQLite_remove_column() {
local lTable=$1
local lColumn=$2
lTableNew="${lTable}_new_clone"
lColumnNew=$(GSQLite_list_column "$lTable" "$lColumn")
GSQLite_clone_table "$lTable" "$lTableNew" "$lColumnNew"
GSQLite_drop_table "$lTable"
GSQLite_rename_table "$lTableNew" "$lTable"
}
#================================================
GSQLite_alter_column() {
local lTable=$1
local lColumn=$2
lQuery="alter table $lTable alter column $lColumn;"
GSQLite_query "$lQuery"
}
#================================================
GSQLite_modify_column() {
local lTable=$1
local lColumn=$2
lQuery="alter table $lTable modify column $lColumn;"
GSQLite_query "$lQuery"
}
#================================================
GSQLite_list_column() {
local lTable=$1
local lRemove=$2
lQuery="pragma table_info($lTable);"
GSQLite_query "$lQuery" | awk -F "|" -v lRemove="$lRemove" '
BEGIN {lFlag = 0}
{if($2 == lRemove) {next}
if(lFlag == 1) {printf(", ")}
lFlag = 1
printf("%s", $2)}'
}
#================================================
GSQLite_set_root() {
export GDATABASE_ROOT=$1
}
#================================================
GSQLite_set_name() {
export GDATABASE_NAME=$1
}
#================================================
GSQLite_set_path() {
local lPath=$1
lRoot=$(gz_string dirname "$lPath")
lName=$(gz_string filename "$lPath")
GSQLite_set_root "$lRoot"
GSQLite_set_name "$lName"
}
#================================================
GSQLite_get_path() {
echo $GDATABASE_PATH
}
#================================================
GSQLite_main "$@"
#================================================
