#!/bin/bash
#================================================
GPWD=$PWD
#================================================
lCheckIn="GPATH" ; if [ "${!lCheckIn}" = "" ] || ! [ -d "${!lCheckIn}" ] ; then echo "ERREUR : ${lCheckIn} ?" ; exit ; fi 
#================================================
. $GPATH/.config
#================================================
lCheckIn="GTEST_ROOT" ; if [ "${!lCheckIn}" = "" ] || ! [ -d "${!lCheckIn}" ] ; then echo "ERREUR : ${lCheckIn} ?" ; exit ; fi 
#================================================
lArgIn="$1" ; lArgName="nom_projet" ; if [ -z "${lArgIn}" ] ; then echo "ERREUR : ${lArgName} ?" ; exit ; fi
#================================================
lProjectName=$1
#================================================
# Configurations
printf "\n"
printf "Configurations :\n"
printf "\t%-20s : %s\n" "GTEST_ROOT" "$GTEST_ROOT"
printf "\t%-20s : %s\n" "nom_projet" "$lProjectName"
printf "\n"
#================================================
read -p "Confirmation (Oui|[N]on) ? " lAnswer
case $lAnswer in
    [Oo]* ) echo "OUI : operation effectuee" ; echo ;;
    * ) echo "NON : operation annulee" ; echo ; exit ;;
esac
#================================================
cd $GTEST_ROOT/$lProjectName/unix
make clean
#================================================
cd $GPWD
#================================================
