#!/bin/bash
#================================================
GPROCESS=$1
#================================================
GVHOSTS_FILE=/etc/apache2/sites-available/000-default.conf
#================================================
GProcess_main() {
if [ "$GPROCESS" = "" ] ; then GProcess_help "$@"
elif [ "$GPROCESS" = "test" ] ; then GProcess_test "$@"
elif [ "$GPROCESS" = "cat" ] ; then GProcess_cat "$@"
elif [ "$GPROCESS" = "nano" ] ; then GProcess_nano "$@"
else GProcess_help "$@";fi
}
#================================================
GProcess_help() {
echo "$FUNCNAME"
}
#================================================
GProcess_test() {
echo "$FUNCNAME"
}
#================================================
GProcess_cat() {
cat $GVHOSTS_FILE
}
#================================================
GProcess_nano() {
nano $GVHOSTS_FILE
}
#================================================
GProcess_main "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" 
#================================================
