#!/bin/bash
#================================================
GPWD=$PWD
#================================================
lCheckIn="GPATH" ; if [ "${!lCheckIn}" = "" ] || ! [ -d "${!lCheckIn}" ] ; then echo "ERREUR : ${lCheckIn} ?" ; exit ; fi 
#================================================
. $GPATH/.config
#================================================
sudo systemctl restart sshd.service
sudo systemctl status sshd.service
#================================================
cd $GPWD
#================================================
