#!/bin/bash
#================================================
GPWD=$PWD
#================================================
G_STATE="S_INIT"
#================================================
GApache_Main() {
while [ 1 ] ; do
case "$G_STATE" in 
    "S_ADMIN") GApache_ADMIN ;;
    "S_INIT") GApache_INIT ;;
    "S_METHOD") GApache_METHOD ;;
    "S_CHOICE") GApache_CHOICE ;;
    #
    "S_MODULE_LIST") GApache_MODULE_LIST ;;
    #
    "S_MODULE_LIST_FILTER_MODULE_FILTER") GApache_MODULE_LIST_FILTER_MODULE_FILTER ;;
    "S_MODULE_LIST_FILTER") GApache_MODULE_LIST_FILTER ;;
    #
    "S_SAVE") GApache_SAVE ;;
    "S_LOAD") GApache_LOAD ;;
    "S_QUIT") GApache_QUIT ;;
    *) break ;;
esac    
done
}
#================================================
GApache_ADMIN() {
gz_admin
G_STATE="S_END"
}
#================================================
GApache_INIT() {
printf "\n"
printf "APACHE !!!\n"
printf "\t%2s : %s\n" "-q" "quitter l'application"
printf "\t%2s : %s\n" "-i" "reinitialiser l'application"
printf "\t%2s : %s\n" "-a" "redemarrer l'administration"
printf "\t%2s : %s\n" "-v" "valider les configurations"
printf "\n"
G_STATE="S_LOAD"
}
#================================================
GApache_METHOD() {
printf "APACHE :\n"
printf "\t%2s : %s\n" "1" "lister les modules"
printf "\t%2s : %s\n" "2" "lister les modules par filtre"
printf "\n"
G_STATE="S_CHOICE"
}
#================================================
GApache_CHOICE() {
read -p "APACHE ($G_APACHE_ID) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_APACHE_ID" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
#
elif [ "$lAnswer" = "1" ] ; then G_STATE="S_MODULE_LIST" ; G_APACHE_ID="$lAnswer"
elif [ "$lAnswer" = "2" ] ; then G_STATE="S_MODULE_LIST_FILTER_MODULE_FILTER" ; G_APACHE_ID="$lAnswer"
fi
}
#================================================
GApache_MODULE_LIST_FILTER_MODULE_FILTER() {
read -p "G_MODULE_FILTER ($G_MODULE_FILTER) ? " lAnswer
if [ "$lAnswer" = "" ] ; then lAnswer="$G_MODULE_FILTER" ; fi
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT" 
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "-v" ] ; then G_STATE="S_MODULE_LIST_FILTER" ; G_MODULE_FILTER="$lAnswer"
elif [ "$lAnswer" != "" ] ; then G_STATE="S_MODULE_LIST_FILTER" ; G_MODULE_FILTER="$lAnswer"
fi
}
#================================================
GApache_MODULE_LIST_FILTER() {
echo
apache2ctl -M | grep -iE "$G_MODULE_FILTER"
G_STATE="S_SAVE" 
}
#================================================
GApache_MODULE_LIST() {
echo
apache2ctl -M
G_STATE="S_SAVE"
}
#================================================
GApache_SAVE() {
gz_process_in "config_save" "G_APACHE_ID" "$G_APACHE_ID"
gz_process_in "config_save" "G_MODULE_FILTER" "$G_MODULE_FILTER"
G_STATE="S_QUIT"
}
#================================================
GApache_LOAD() {
G_APACHE_ID=$(gz_process_in "config_load" "G_APACHE_ID")
G_MODULE_FILTER=$(gz_process_in "config_load" "G_MODULE_FILTER")
G_STATE="S_METHOD"
}
#================================================
GApache_QUIT() {
echo
read -p "QUIT (Oui/[N]on) ? " lAnswer
if [ "$lAnswer" = "-q" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "-i" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "-a" ] ; then G_STATE="S_ADMIN"
elif [ "$lAnswer" = "o" ] ; then G_STATE="S_END"
elif [ "$lAnswer" = "n" ] ; then G_STATE="S_INIT"
elif [ "$lAnswer" = "" ] ; then G_STATE="S_INIT"
fi
}
#================================================
GApache_Main
#================================================
cd $GPWD
#================================================
