#!/bin/bash
#================================================
GPWD=$PWD
#================================================
lCheckIn="GPATH" ; if [ "${!lCheckIn}" = "" ] || ! [ -d "${!lCheckIn}" ] ; then echo "ERREUR : ${lCheckIn} ?" ; exit ; fi 
#================================================
. $GPATH/.config
#================================================
lCheckIn="GBIN_PATH" ; if [ "${!lCheckIn}" = "" ] || ! [ -d "${!lCheckIn}" ] ; then echo "ERREUR : ${lCheckIn} ?" ; exit ; fi 
#================================================
lArgIn="$1" ; lArgName="nom_script" ; if [ -z "${lArgIn}" ] ; then echo "ERREUR : ${lArgName} ?" ; exit ; fi
#================================================
G_SCRIPT_FILE=$1
G_PATH=$GBIN_PATH/msys
#================================================
# Configurations
printf "\n"
printf "Configurations :\n"
printf "\t%-20s : %s\n" "G_PATH" "$G_PATH"
printf "\t%-20s : %s\n" "G_SCRIPT_FILE" "$G_SCRIPT_FILE"
printf "\n"
#================================================
read -p "Confirmation (Oui|[N]on) ? " lAnswer
case $lAnswer in
    [Oo]* ) echo "OUI : operation effectuee" ; echo ;;
    * ) echo "NON : operation annulee" ; echo ; exit ;;
esac
#================================================
cd $G_PATH
echo '#!/bin/bash
#================================================
GPWD=$PWD
#================================================
lCheckIn="GPATH" ; if [ "${!lCheckIn}" = "" ] || ! [ -d "${!lCheckIn}" ] ; then echo "ERREUR : ${lCheckIn} ?" ; exit ; fi 
#================================================
. $GPATH/.config
#================================================

#================================================
cd $GPWD
#================================================' > $G_SCRIPT_FILE
chmod 777 $G_SCRIPT_FILE
#================================================
cd $GPWD
#================================================
