#!/bin/bash
#================================================
GPWD=$PWD
#================================================
GPATH=$(gz_config get GPATH) ; . $GPATH/.config
#================================================
lCheckIn="GBIN_PATH" ; if [ "${!lCheckIn}" = "" ] || ! [ -d "${!lCheckIn}" ] ; then echo $(gz_color s "$lCheckIn ?" yellow fg) ; exit ; fi 
#================================================
GMd5_main() {
lArgSize="$#"
if [ "$lArgSize" = "0" ] ; then GMd5_help "$@"
else GMd5_process "$@" ; fi
}
#================================================
GMd5_help() {
lScript=$(gz_string filename "$0")
GSCRIPT="\t\033[0;35m${lScript}\033[0m"
GCOMMENT="\033[0;33m%s\033[0m"
GHELP="$GSCRIPT : $GCOMMENT\n"
GREQUEST="\033[36m%s\033[0m"
GPROCESS="$GSCRIPT $GREQUEST : $GCOMMENT\n"
printf "\n"
printf "%s\n" "Description:"
printf "\t%s\n" "Operations sur le cryptage des chaines."
printf "\n"
printf "%s\n" "Utilisation:"
printf "$GHELP" "afficher aide"
printf "$GPROCESS" "h <string_in>" "crypter une chaine"
printf "\n"
}
#================================================
GMd5_process() {
lArgSize="$#"
lArgCount=1
lRunFlag=0
while [ 1 ] ; do
if [ "$lArgCount" -gt "$lArgSize" ] ; then break ; fi
lKey=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
# h
if [ "$lKey" = "h" ] ; then 
lString=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
GMd5_hash "$lString" ; lRunFlag=1
#
fi
done
if [ "$lRunFlag" = "0" ] ; then GMd5_help ; fi 
}
#================================================
GMd5_hash() {
local lString=$1
echo -n "$lString" | md5sum | awk '{print $1}'
}
#================================================
GMd5_main "$@"
#================================================
