@echo off 
::===============================================
set "GCYGWIN_BIN=C:\cygwin64\bin"
set "GDEV_PATH=C:\Users\Admin\Downloads\Programs\ReadyDev"
set "GTEST_BUILD=C:\Users\Admin\Downloads\Programs\ReadyTest\opencv\learn_opencv\age_gender\win"
set "GNU_WIN32=C:\Users\Admin\Downloads\Programs\ReadyLib\dev\gnuwin32\0.6.3\bin"
set "GBIN_UTILS=C:\Users\Admin\Downloads\Programs\ReadyLib\dev\binutils\2.34\mingw32\bin"
set "GBIN_PATH=C:\Users\Admin\Downloads\Programs\ReadyBin"
set "GLIB_PATH=C:\Users\Admin\Downloads\Programs\ReadyLib"
set "GPKGCONFIG_BIN=C:\Users\Admin\Downloads\Programs\ReadyLib\dev\pkgconfig\0.29.2\mingw32\bin"
set "GCPP_PATH=C:\Users\Admin\Downloads\Programs\ReadyCpp"
set "GCPP_BUILD=C:\Users\Admin\Downloads\Programs\ReadyCpp\win"
set "GC_PATH=C:\Users\Admin\Downloads\Programs\ReadyC"
set "GC_BUILD=C:\Users\Admin\Downloads\Programs\ReadyC\win"
set "GMUPARSER_BIN=C:\Users\Admin\Downloads\Programs\ReadyLib\dev\muparser\mingw\bin"
set "GOPENCV_BIN=C:\Users\Admin\Downloads\Programs\ReadyLib\dev\opencv\mingw\bin"
set "GMINGW_BIN=C:\MinGW\bin"
set "GMINGW_W64=C:\mingw-w64\i686-8.1.0-win32-dwarf-rt_v6-rev0\mingw32\bin"
set "GMINGW_QT=C:\Qt\Qt5.8.0\Tools\mingw530_32\bin"
set "GCMAKE_BIN=C:\Program Files\CMake\bin"
set "GGTK_BIN=C:\Users\Admin\Downloads\Programs\ReadyLib\dev\gtk\3.6.4\mingw32\bin"
::===============================================
