set "GMINGW_PATH=C:\MinGW\bin"
set "GC_BUILD=C:\Users\Admin\Downloads\Programs\ReadyC\win"
set "GBIN_PATH=C:\Users\Admin\Downloads\Programs\ReadyBin"
set "GC_PATH=C:\Users\Admin\Downloads\Programs\ReadyC"
set "GDEV_PATH=C:\Users\Admin\Downloads\Programs\ReadyDev"
