#!/bin/bash
#================================================
GPWD=$PWD
#================================================
GPATH=$(gz_config get GPATH)
GHTTPD_CONF=$(gz_config get GHTTPD_CONF)
#================================================
lCheckIn="GHTTPD_CONF" ; if [ "${!lCheckIn}" = "" ] || ! [ -f "${!lCheckIn}" ] ; then echo $(gz_color s "$lCheckIn ?" yellow fg) ; exit ; fi 
lCheckIn="GPATH" ; if [ "${!lCheckIn}" = "" ] || ! [ -d "${!lCheckIn}" ] ; then echo $(gz_color s "$lCheckIn ?" yellow fg) ; exit ; fi 
#================================================
export AWKPATH="$GPATH/awk"
#================================================
GPhp_main() {
lArgSize="$#"
if [ "$lArgSize" = "0" ] ; then GPhp_help "$@"
else GPhp_process "$@" ; fi
}
#================================================
GPhp_help() {
lScript=$(gz_string filename "$0")
GSCRIPT="\t\033[0;35m${lScript}\033[0m"
GCOMMENT="\033[0;33m%s\033[0m"
GHELP="$GSCRIPT : $GCOMMENT\n"
GREQUEST="\033[36m%s\033[0m"
GPROCESS="$GSCRIPT $GREQUEST : $GCOMMENT\n"
printf "\n"
printf "%s\n" "Description:"
printf "\t%s\n" "Operations sur les commandes awk."
printf "\n"
printf "%s\n" "Utilisation:"
printf "$GHELP" "afficher aide"
printf "$GPROCESS" "test <module_in>" "tester module"
printf "\n"
}
#================================================
GPhp_process() {
lArgSize="$#"
lArgCount=1
lRunFlag=0
while [ 1 ] ; do
if [ "$lArgCount" -gt "$lArgSize" ] ; then break ; fi
lKey=${!lArgCount} ; lArgCount=$(gz_string math "$lArgCount + 1")
# test
if [ "$lKey" = "test" ] ; then 
GPhp_test ; lRunFlag=1
#
fi
done
if [ "$lRunFlag" = "0" ] ; then GPhp_help ; fi 
}
#================================================
GPhp_test() {
GPhp_listen
}
#================================================
GPhp_listen() {
awk -i gk_string '
BEGIN {}{
lLine = $0
if(lLine == "") next
lFirstChar = gk_
if(lLine == "") next
printf("%d : %s\n" NR, lLine)
} END {}' $GHTTPD_CONF
}
#================================================
GPhp_main "$@"
#================================================
